(define flash-asm
  `((label write-flash-byte)
    (push bc)
    (ld b a)
    (push af)
    (ld a i)
    (push af)
    (di)
    (ld a b)
    ,@(push* '(hl de bc hl de bc))

    (ld hl write-flash-byte-ram)
    (ld de flash-executable-ram)
    (ld bc #x1f)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    ,@(pop* '(bc de hl af))
    (jp po local-label1)
    (ei)
    (label local-label1)
    ,@(pop* '(af bc))
    (ret)
    (label write-flash-byte-ram)
    (and (hl))
    (ld b a)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld (hl) b)
    (label local-label2)
    (ld a b)
    (xor (hl))
    (bit 7 a)
    (jr z write-flash-byte-done)
    (bit 5 (hl))
    (jr z local-label2)
    (label write-flash-byte-done)
    (ld (hl) #xf0)
    (ret)

    (label write-flash-byte-ram-end)

    (label write-flash-buffer)
    (push af)
    (ld a i)
    (push af)
    (di)
    ,@(push* '(hl de bc hl de bc))
    (ld hl write-flash-buffer-ram)
    (ld de flash-executable-ram)
    (ld bc #x2c)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    ,@(pop* '(bc de hl af))
    (jp po local-label3)
    (ei)
    (label local-label3)
    (pop af)
    (ret)

    (label write-flash-buffer-ram)
    (label write-flash-buffer-loop)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld a (hl))
    (ld (de) a)
    (inc de)
    (dec bc)

    (label local-label4)
    (xor (hl))
    (bit 7 a)
    (jr z local-label5)
    (bit 5 a)
    (jr z local-label4)
    (ld a #xf0)
    (ld (0) a)
    (ret)
    (label local-label5)
    (inc hl)
    (ld a b)
    (or a)
    (jr nz write-flash-buffer-loop)
    (ld a c)
    (or a)
    (jr nz write-flash-buffer-loop)
    (ret)

    (label write-flash-buffer-ram-end)

    (label erase-flash-sector)
    (push bc)
    (ld b a)
    (push af)
    (ld a i)
    (ld a i)
    (push af)
    (di)
    (ld a b)
    ,@(push* '(hl de bc hl de bc))
    (ld hl erase-flash-sector-ram)
    (ld de flash-executable-ram)
    (ld bc #x30)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    ,@(pop* '(bc de hl af))
    (jp po local-label6)
    (ei)
    (label local-label6)
    (pop af)
    (pop bc)
    (ret)

    (label erase-flash-sector-ram)
    (out (6) a)
    (ld a #xaa)
    (ld (#x0aaa) a)
    (ld a #x55)
    (ld (#x0555) a)
    (ld a #x80)
    (ld (#x0aaa) a)
    (ld a #xaa)
    (ld (#x0aaa) a)
    (ld a #x55)
    (ld (#x0555) a)
    (ld a #x30)
    (ld (#x4000) a)
    (label local-label7)
    (ld a (#x4000))
    (bit 7 a)
    (ret nz)
    (bit 5 a)
    (jr z local-label7)
    (ld a #xf0)
    (ld (#x4000) a)
    (ret)
    (label erase-flash-sector-ram-end)

    (label erase-flash-page)
    ,@(push* '(af bc af))
    (call copy-sector-to-swap)
    (pop af)
    (push af)
    (call erase-flash-sector)
    (pop af)
    (ld c a)
    (and #b11111100)
    (ld b ,swap-sector)
    (label local-label8)
    (cp c)
    (jr z local-label9)
    (call #x32d)
    (label local-label9)
    (inc b)
    (inc a)
    (push af)
    (ld a b)
    (and #b11111100)
    (or a)
    (jr z local-label10)
    (pop af)
    (jr local-label8)
    (label local-label10)
    ,@(pop* '(af bc af))
    (ret)

    (label erase-flash-page-ram)
    (label copy-sector-to-swap)
    (push af)
    ;; (db (#xff #xff #xff))
    (ld a ,swap-sector)
    (call erase-flash-sector)
    (pop af)
    (push bc)
    (ld b a)
    (push af)
    (ld a i)
    (ld a i)
    (push af)
    (di)
    (ld a b)
    (and #b11111100)
    (push hl)
    (push de)
    ;; (ld hl copy-sector-to-swap-ram)
    (ld hl #x2db)
    (push af)
    (ld a 1)
    (out (5) a)
    (ld de #xc000)
    (ld bc #x52)
    (ldir)
    (pop af)
    (ld hl #x4000)
    (add hl sp)
    (ld sp hl)
    (call #xc000)
    (xor a)
    (out (5) a)
    (ld hl 0)
    (add hl sp)
    (ld bc #x4000)
    (or a)
    (sbc hl bc)
    (ld sp hl)
    ,@(pop* '(de hl af))
    (jp po local-label11)
    (ei)
    (label local-label11)
    (pop af)
    (pop bc)
    (ret)
    (label copy-sector-to-swap-ram)
    (out (7) a)
    (ld a ,swap-sector)
    (out (6) a)
    (label copy-sector-to-swap-preloop)
    (ld hl #x8000)
    (ld de #x4000)
    (ld bc #x4000)
    (label copy-sector-to-swap-loop)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld a (hl))
    (ld (de) a)
    (inc de)
    (dec bc)
    (label local-label12)
    (xor (hl))
    (bit 7 a)
    (jr z local-label13)
    (bit 5 a)
    (jr z local-label12)
    (ld a #xf0)
    (ld (0) a)
    (ld a #x81)
    (out (7) a)
    (ret)
    (label local-label13)
    (inc hl)
    (ld a b)
    (or a)
    (jr nz copy-sector-to-swap-loop)
    (ld a c)
    (or a)
    (jr nz copy-sector-to-swap-loop)
    (in a (7))
    (inc a)

    (out (7) a)
    (in a (6))
    (inc a)
    (out (6) a)
    (and #b00000011)
    (or a)
    (jr nz copy-sector-to-swap-preloop)
    (ld a #x81)
    (out (7) a)
    (ret)

    (label copy-flash-page)
    (push de)
    (ld d a)
    (push af)
    (ld a i)
    (ld a i)
    (push af)
    (di)
    (ld a d)
    ,@(push* '(hl de af bc))
    ;; (ld hl copy-flash-page-ram)
    (ld hl #x36c)
    (ld a 1)
    (out (5) a)
    (ld de #xc000)
    (ld bc #x42)
    (ldir)
    (pop bc)
    (pop af)
    (ld hl #x4000)
    ;; Forgetting a byte?
    (add hl sp)
    (ld sp hl)
    (call #xc000)
    (xor a)
    (out (5) a)
    (ld hl 0)
    (add hl sp)
    (ld bc #x4000)
    (or a)
    (sbc hl bc)
    (ld sp hl)
    ,@(pop* '(de hl bc af))
    (jp po local-label14)
    (ei)
    (label local-label14)
    (pop af)
    (ret)

    (label copy-flash-page-ram)
    (out (6) a)
    (ld a b)
    (out (7) a)

    (label copy-flash-page-preloop)
    (ld hl #x8000)
    (ld de #x4000)
    (ld bc #x4000)
    (label copy-flash-page-loop)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld a (hl))
    (ld (de) a)
    (inc de)
    (dec bc)
    (label local-label15)
    (xor (hl))
    (bit 7 a)
    (jr z local-label16)
    (bit 5 a)
    (jr z local-label15)
    (ld a #xf0)
    (ld (0) a)
    (ld a #x81)
    (out (7) a)
    (ret)
    (label local-label16)
    (inc hl)
    (ld a b)
    (or a)
    (jr nz copy-flash-page-loop)
    (ld a c)
    (or a)
    (jr nz copy-flash-page-loop)
    (ld a #x81)
    (out (7) a)
    (ret)
    (label copy-flash-page-ram-end)

    ))
