;; Text functions

(define text-asm
  `((label newline)
    (push af)
    (ld a e)
    (add a 6)
    (ld e a)
    (ld d b)
    (pop af)
    (ret)

    (label wrap-char)
    (push ix)
    (db (#xdd))
    (ld l 0)
    (call wrap-char-shared)
    (pop ix)
    (ret)

    (label wrap-char-and)
    (push ix)
    (db (#xdd))    
    (ld l 1)
    (call wrap-char-shared)
    (pop ix)
    (ret)

    (label wrap-char-xor)
    (push ix)
    (db (#xdd))
    (ld l 2)
    (call wrap-char-shared)
    (pop ix)
    (ret)

    (label draw-char)
    (push ix)
    (db (#xdd))
    (ld l 0)
    (call draw-char-shared)
    (pop ix)
    (ret)

    (label draw-char-and)
    (push ix)
    (db (#xdd))
    (ld l 1)
    (call draw-char-shared)
    (pop ix)
    (ret)

    (label draw-char-xor)
    (push ix)
    (db (#xdd))
    (ld l 2)
    (call draw-char-shared)
    (pop ix)
    (ret)

    (label draw-char-shared)
    ,@(push* '(af hl bc))
    (cp ,(char->integer #\newline))
    (jr nz local-labeldcs)
    (ld a e)
    (add a 6)
    (ld e a)
    (ld d b)
    (jr dcs-exit)
    (label local-labeldcs)

    (cp ,(char->integer #\tab))
    (jr nz local-label22)
    (ld a d)
    (add a 6)
    (ld d a)
    (jr dcs-exit)
    
    (label local-label22)
    (push de)
    (sub #x20)
    (ld l a)
    (ld h 0)
    (add hl hl)
    (ld d h)
    (ld e l)
    (add hl hl)
    (add hl de)
    ((ex de hl))
    (ld hl kernel-font)
    (add hl de)
    (ld a (hl))
    (inc hl)
    (pop de)
    (ld b 5)
    (push af)
    (ld a d)
    (cp 95)
    (jr nc local-label23)
    (db (#xdd))
    (ld a l)
    (or a)
    (call z put-sprite-or)
    (dec a)
    (call z put-sprite-and)
    (dec a)
    (call z put-sprite-xor)
    (pop af)
    (add a d)
    (ld d a)
    
    (label dcs-exit)
    ,@(pop* '(bc hl af))
    (ret)
    (label local-label23)
    ,@(pop* '(af bc hl af))
    (ret)

    (label wrap-char-shared)
    ,@(push* '(af bc hl))
    (cp ,(char->integer #\newline))
    (jr nz local-label24)
    (ld a e)
    (add a 6)
    (ld e a)
    (db (#xdd))
    (ld d h)
    (jr wcs-exit)

    (label local-label24)
    (cp ,(char->integer #\tab))
    (jr nz local-label25)
    (ld a d)
    (add a 6)
    (ld d a)
    (jr wcs-exit)

    (label local-label25)
    (push de)
    (sub #x20)
    (ld l a)
    (ld h 0)
    (add hl hl)
    (ld d h)
    (ld e l)
    (add hl hl)
    (add hl de)
    ((ex de hl))
    (ld hl kernel-font)
    (add hl de)
    (ld a (hl))
    (inc hl)
    (pop de)

    (add a d)
    (cp b)
    (jr c local-label26)
    (ld a e)
    (add a 6)
    (ld e a)
    (db (#xdd))
    (ld d h)
    
    (label local-label26)
    (ld a e)
    (cp c)
    (jr nc local-label27)
    (ld b 5)
    (db (#xdd))
    (ld a l)
    (or a)
    (call z put-sprite-or)
    (dec a)
    (call z put-sprite-and)
    (dec a)
    (call z put-sprite-xor)
    (dec hl)
    (ld a (hl))
    (add a d)
    (ld d a)

    (label wcs-exit)
    ,@(pop* '(hl bc af))
    (ret)
    
    (label local-label27)
    (ld e c)
    (jr wcs-exit)

    (label draw-str)
    (push ix)
    (db (#xdd))
    (ld l 0)
    (call draw-str-shared)
    (pop ix)
    (ret)

    (label draw-str-and)
    (push ix)
    (db (#xdd))
    (ld l 1)
    (call draw-str-shared)
    (pop ix)
    (ret)

    (label draw-str-xor)
    (push ix)
    (db (#xdd))
    (ld l 2)
    (call draw-str-shared)
    (pop ix)
    (ret)

    (label draw-str-shared)
    (push hl)
    (push af)
    (label local-label28)
    (ld a (hl))
    (or a)
    (jr z local-label29)
    (call draw-char-shared)
    (inc hl)
    (jr local-label28)
    
    (label local-label29)
    (pop af)
    (pop hl)
    (ret)

    (label draw-dec-a)
    ,@(push* '(af bc hl))
    (ld c 0)
    (push af)
    (push de)
    (ld e 100)
    (ld d a)
    (call div-8-by-8)
    (ld a d)
    (pop de)
    (or a)
    (jr z no-100)
    (inc c)
    (ld b a)
    (add a ,(char->integer #\0))
    (call draw-char)
    (ld a b)
    (ld b e)
    (ld e a)
    (ld h 100)
    (call mul-8-by-8)
    (ld e b)
    (pop af)
    (sub l)
    (jr done-100)
    (label no-100)
    (pop af)
    
    (label done-100)
    (push af)
    (push de)
    (ld e 10)
    (ld d a)
    (call div-8-by-8)
    (ld a d)
    (pop de)
    (ld b a)
    (or a)
    (or c)
    (ld a b)
    (jr z no-10)
    (ld b a)
    (add a ,(char->integer #\0))
    (call draw-char)
    (ld a b)
    (ld b e)
    (ld e a)
    (ld h 10)
    (call mul-8-by-8)
    (ld e b)
    (pop af)
    (sub l)
    (jr done-10)
    (label no-10)
    (pop af)

    (label done-10)
    (add a ,(char->integer #\0))
    (call draw-char)
    (pop hl)
    (pop bc)
    (pop af)
    (ret)
    

    (label draw-dec-hl)
    (push hl)
    (push bc)
    (push af)
    (ld b 0)
    (label dd-hl-loop)
    (push de)
    (ld de 0)
    (call cp-hl-de)
    (pop de)
    (jr z dd-hl-local)
    (ld c 10)
    (call div-hl-by-c)
    (push af)
    (inc b)
    (jr dd-hl-loop)
    (label dd-hl-local)
    (ld a b)
    (cp 0)
    (call z draw-dec-a)
    (label dd-hl-draw)
    (ld a b)
    (cp 0)
    (jr z dd-hl-local2)
    (pop af)
    (call draw-dec-a)
    (dec b)
    (jr dd-hl-draw)

    (label dd-hl-local2)
    (pop af)
    (pop bc)
    (pop hl)
    (ret)

    (label wrap-str)
    (push ix)
    (db (#xdd))
    (ld h a)
    (db (#xdd))
    (ld l 0)
    (call wrap-str-shared)
    (pop ix)
    (ret)

    (label wrap-str-shared)
    (push af)
    (label wss-local1)
    (ld a (hl))
    (or a)
    (jr z wss-local2)
    (call wrap-char-shared)
    (ld a e)
    (cp c)
    (jr nc wss-local2)
    (inc hl)
    (jr wss-local1)
    
    (label wss-local2)
    (pop af)
    (ret)
    ))
