\ Run from a disposable flash page, with all test words in fixed RAM.
VARIABLE CHECKS VARIABLE FAILURES VARIABLE DONE
VARIABLE SAVED-DP VARIABLE SAVED-LATEST
VARIABLE ACTUAL VARIABLE EXPECTED
CREATE ERRORS 512 ALLOT
0 CHECKS ! 0 FAILURES ! 0 DONE !
: ASSERT
  1 CHECKS +! 0= IF
    FAILURES @ 80 < IF
      ERRORS FAILURES @ 6 * + DUP >R CHECKS @ SWAP !
      ACTUAL @ R@ 2 + ! EXPECTED @ R> 4 + !
    THEN 1 FAILURES +!
  THEN ;
: CHECK= DUP EXPECTED ! OVER ACTUAL ! = ASSERT ;
: RESTORE SAVED-DP @ DP ! SAVED-LATEST @ LATEST ! 0 STATE ! ;
: SAME HERE SAVED-DP @ CHECK= LATEST @ SAVED-LATEST @ CHECK= ;
: TRY-EVAL ['] EVALUATE CATCH DUP IF >R 2DROP R> THEN ;
: BYTE 90 C, ;
: CELL 4660 , ;
: GROW 1 ALLOT ;
: SHRINK -1 ALLOT ;
: HUGE -32768 ALLOT ;
: NOOP 0 ALLOT ;
: HUGE-ROOM 65535 ROOM ;
: MAKE-CREATE S" CREATE ZZ" TRY-EVAL ;
: MAKE-VARIABLE S" VARIABLE ZZ" TRY-EVAL ;
: MAKE-CONSTANT S" 7 CONSTANT ZZ" TRY-EVAL ;
: MAKE-VALUE S" 7 VALUE ZZ" TRY-EVAL ;

\ The quote at offset 5 is outside a source limited to five bytes.
HERE 83 C, 34 C, 32 C, 88 C, 89 C, 34 C, CONSTANT QUOTED
HERE 83 C, 34 C, 32 C, 34 C, CONSTANT EMPTY-QUOTED
: QUOTE-RESULT QUOTED 6 TRY-EVAL DUP 0= IF DROP 2DROP 0 THEN ;
: COMPILE-QUOTE
  SOURCE 2>R >IN @ >R STATE @ >R
  QUOTED 6 SOURCE! 3 >IN ! 1 STATE !
  ['] S" CATCH
  R> STATE ! R> 2R> SOURCE! >IN ! ;
: NAMES
  S" CREATE" TRY-EVAL -16 CHECK= SAME
  S" :" TRY-EVAL -16 CHECK= SAME
  S" VARIABLE" TRY-EVAL -16 CHECK= SAME
  S" 7 CONSTANT" TRY-EVAL -16 CHECK= SAME
  S" 7 VALUE" TRY-EVAL -16 CHECK= SAME
  S" [CHAR]" TRY-EVAL -16 CHECK= SAME
  S" CREATE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" TRY-EVAL -19 CHECK= SAME
  S" : AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" TRY-EVAL -19 CHECK= SAME
  S" VARIABLE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" TRY-EVAL -19 CHECK= SAME
  S" 7 CONSTANT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" TRY-EVAL -19 CHECK= SAME
  S" 7 VALUE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" TRY-EVAL -19 CHECK= SAME
;
: STRINGS
  QUOTED 5 TRY-EVAL -18 CHECK= SAME
  QUOTED 6 TRY-EVAL 0 CHECK=
  2 CHECK= DUP HERE CHECK= DUP C@ 88 CHECK= 1+ C@ 89 CHECK= SAME
  DP-LIMIT DP ! QUOTE-RESULT -8 CHECK= HERE DP-LIMIT CHECK=
  DP-LIMIT C@ 165 CHECK=
  EMPTY-QUOTED 4 TRY-EVAL 0 CHECK= 0 CHECK= DP-LIMIT CHECK=
  DP-LIMIT C@ 165 CHECK=
  DP-LIMIT 2 - DP ! QUOTED 6 TRY-EVAL 0 CHECK=
  2 CHECK= DUP HERE CHECK= DUP C@ 88 CHECK= 1+ C@ 89 CHECK=
  HERE DP-LIMIT 2 - CHECK= DP-LIMIT C@ 165 CHECK=
  DP-LIMIT 6 - DP ! 77 HERE C!
  COMPILE-QUOTE -8 CHECK= HERE DP-LIMIT 6 - CHECK= HERE C@ 77 CHECK=
  DP-LIMIT 7 - DP ! COMPILE-QUOTE 0 CHECK=
  HERE DP-LIMIT CHECK= DP-LIMIT 3 - C@ 88 CHECK=
  DP-LIMIT 2 - C@ 89 CHECK= DP-LIMIT 1- C@ 0 CHECK=
  DP-LIMIT C@ 165 CHECK= RESTORE SAME
;
: DEFINITIONS
  DP-LIMIT 8 - DP ! MAKE-CREATE -8 CHECK=
  HERE DP-LIMIT 8 - CHECK= LATEST @ SAVED-LATEST @ CHECK=
  DP-LIMIT 9 - DP ! MAKE-CREATE 0 CHECK= HERE DP-LIMIT CHECK=
  S" ' ZZ >BODY" TRY-EVAL 0 CHECK= DP-LIMIT CHECK= RESTORE
  DP-LIMIT 10 - DP ! MAKE-VARIABLE -8 CHECK=
  HERE DP-LIMIT 10 - CHECK= LATEST @ SAVED-LATEST @ CHECK=
  DP-LIMIT 11 - DP ! MAKE-VARIABLE 0 CHECK= HERE DP-LIMIT CHECK=
  S" ZZ @" TRY-EVAL 0 CHECK= 0 CHECK= RESTORE
  DP-LIMIT 14 - DP ! MAKE-CONSTANT -8 CHECK=
  HERE DP-LIMIT 14 - CHECK= LATEST @ SAVED-LATEST @ CHECK=
  DP-LIMIT 15 - DP ! MAKE-CONSTANT 0 CHECK= HERE DP-LIMIT CHECK=
  S" ZZ" TRY-EVAL 0 CHECK= 7 CHECK= RESTORE
  DP-LIMIT 14 - DP ! MAKE-VALUE -8 CHECK=
  HERE DP-LIMIT 14 - CHECK= LATEST @ SAVED-LATEST @ CHECK=
  DP-LIMIT 15 - DP ! MAKE-VALUE 0 CHECK= HERE DP-LIMIT CHECK=
  S" ZZ" TRY-EVAL 0 CHECK= 7 CHECK= RESTORE
  DP-LIMIT C@ 165 CHECK= SAME
;
: ALLOCATIONS
  DP-LIMIT 1- DP ! 77 HERE C!
  ['] CELL CATCH -8 CHECK= HERE DP-LIMIT 1- CHECK= HERE C@ 77 CHECK=
  BYTE HERE DP-LIMIT CHECK= DP-LIMIT 1- C@ 90 CHECK=
  ['] BYTE CATCH -8 CHECK= ['] CELL CATCH -8 CHECK=
  ['] GROW CATCH -8 CHECK= ['] NOOP CATCH 0 CHECK=
  HERE DP-LIMIT CHECK= DP-LIMIT C@ 165 CHECK=
  DP-LIMIT 2 - DP ! CELL HERE DP-LIMIT CHECK= DP-LIMIT 2 - @ 4660 CHECK=
  DP-LIMIT 4 - DP ! 77 HERE C!
  ['] DOES> CATCH -8 CHECK= HERE DP-LIMIT 4 - CHECK= HERE C@ 77 CHECK=
  DP-LIMIT 5 - DP ! ['] DOES> CATCH 0 CHECK= HERE DP-LIMIT CHECK=
  DP-LIMIT C@ 165 CHECK=
  RESTORE 16 ALLOT HERE SAVED-DP @ 16 + CHECK=
  -16 ALLOT SAME
  H0 DP ! ['] SHRINK CATCH -8 CHECK= HERE H0 CHECK=
  H0 1- DP ! ['] NOOP CATCH -8 CHECK= HERE H0 1- CHECK=
  DP-LIMIT 1+ DP ! ['] NOOP CATCH -8 CHECK= HERE DP-LIMIT 1+ CHECK=
  RESTORE ['] HUGE CATCH -8 CHECK= ['] HUGE-ROOM CATCH -8 CHECK= SAME
;
: BANKS
  TEST-BANK@ >R
  0 MAP-FLASH -1 CHECK= TEST-BANK@ 0 CHECK=
  7 MAP-FLASH -1 CHECK= TEST-BANK@ 7 CHECK=
  63 MAP-FLASH -1 CHECK= TEST-BANK@ 63 CHECK=
  64 MAP-FLASH 0 CHECK= TEST-BANK@ 63 CHECK=
  256 MAP-FLASH 0 CHECK= TEST-BANK@ 63 CHECK=
  65535 MAP-FLASH 0 CHECK= TEST-BANK@ 63 CHECK=
  256 SET-RAM-MEMA 0 CHECK= TEST-BANK@ 63 CHECK=
  R> MAP-FLASH DROP
;
: RUN-CHECKS
  DEPTH >R HERE SAVED-DP ! LATEST @ SAVED-LATEST !
  DP-LIMIT 49152 CHECK= USED UNUSED + H0 + DP-LIMIT CHECK=
  DP-LIMIT C@ >R 165 DP-LIMIT C!
  NAMES STRINGS DEFINITIONS ALLOCATIONS BANKS
  DP-LIMIT C@ 165 CHECK= R> DP-LIMIT C!
  SAME DEPTH R> CHECK= 51966 DONE !
;
RUN-CHECKS
PAGE FAILURES @ . ." failures / " CHECKS @ . CR
: HOLD-CHECKS BEGIN AGAIN ; HOLD-CHECKS
