\ Resident service, scoped banking, nested interpreter, and parser regressions.
VARIABLE CORE-CHECKS VARIABLE CORE-FAILURES VARIABLE CORE-DONE
HERE 384 ALLOT CONSTANT CORE-ERRORS
VARIABLE CORE-ACTUAL VARIABLE CORE-EXPECTED
0 CORE-CHECKS ! 0 CORE-FAILURES ! 0 CORE-DONE !
: CORE-ASSERT
  1 CORE-CHECKS +! 0= IF
    CORE-CHECKS @ CORE-ERRORS CORE-FAILURES @ 6 * + DUP >R !
    CORE-ACTUAL @ R@ 2 + ! CORE-EXPECTED @ R> 4 + !
    1 CORE-FAILURES +!
  THEN
;
: CORE-= DUP CORE-EXPECTED ! OVER CORE-ACTUAL ! = CORE-ASSERT ;
BANK@ CONSTANT CORE-BANK
: CORE-PAGE BANK@ ;
: CORE-THROW 99 THROW ;
: CORE-INNER BANK@ 8 CORE-= ;
: CORE-OUTER
  ['] CORE-INNER 8 WITH-PAGE 0 CORE-=
  BANK@ 9 CORE-=
;
' CORE-PAGE 8 WITH-PAGE 0 CORE-= 8 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-PAGE 63 WITH-PAGE 0 CORE-= 63 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-THROW 8 WITH-PAGE 99 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-PAGE 64 WITH-PAGE 10 CORE-=
' CORE-PAGE 65535 WITH-PAGE 10 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-OUTER 9 WITH-PAGE 0 CORE-=
BANK@ CORE-BANK CORE-=
16384 FS-BUF 1 STORAGE-READ 10 CORE-=
65535 FS-BUF 0 STORAGE-READ 10 CORE-=
0 33791 1 STORAGE-READ 10 CORE-=
0 65535 1 STORAGE-READ 10 CORE-=
0 SERVICE@ ' PAGE CORE-=
4 SERVICE@ ' YIELD CORE-=
15 SERVICE@ 0 CORE-=
65535 SERVICE@ 0 CORE-=
UNUSED 3 OS-CALL CORE-=
: CORE-BAD-CALL 15 OS-CALL ;
' CORE-BAD-CALL CATCH 20 CORE-=
: CORE-EVAL-OK S" 2 3 +" DROP EVALUATE0 ;
: CORE-EVAL-BASE S" HEX 17" DROP EVALUATE0 ;
: CORE-EVAL-BAD S" 42 NO-SUCH-CORE-WORD" DROP EVALUATE0 ;
: CORE-EVAL-THROW S" HEX 42 88 THROW" DROP EVALUATE0 ;
: CORE-EVAL-NEST S" CORE-EVAL-OK" DROP EVALUATE0 ;
: CORE-EVAL-LONG S" AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" DROP EVALUATE0 ;
: CORE-EVAL-MAX S" : AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 17 ; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" DROP EVALUATE0 ;
123 CORE-EVAL-OK 0 CORE-= 5 CORE-= 123 CORE-=
\ Numeric input is currently decimal even when BASE changes for output.
CORE-EVAL-BASE 0 CORE-= 17 CORE-= BASE @ 10 CORE-=
CORE-EVAL-BAD 1 CORE-= 42 CORE-=
123 CORE-EVAL-THROW 88 CORE-= 123 CORE-=
BASE @ 10 CORE-=
CORE-EVAL-NEST 0 CORE-= 0 CORE-= 5 CORE-=
CORE-EVAL-LONG 19 CORE-=
WORD-BUF 31 + C@ 0 CORE-=
CORE-EVAL-OK 0 CORE-= 5 CORE-=
CORE-EVAL-MAX 0 CORE-= 17 CORE-=
CORE-EVAL-LONG 19 CORE-=
CORE-EVAL-OK 0 CORE-= 5 CORE-=
: CORE-INPUT-CHECK
  INPUT-PTR @ >R CORE-EVAL-OK 2DROP INPUT-PTR @ R> =
;
CORE-INPUT-CHECK 1 CORE-=
51966 CORE-DONE !
