\ Resident service, scoped banking, nested interpreter, and parser regressions.
VARIABLE CORE-CHECKS VARIABLE CORE-FAILURES VARIABLE CORE-DONE
HERE 576 ALLOT CONSTANT CORE-ERRORS
VARIABLE CORE-ACTUAL VARIABLE CORE-EXPECTED
0 CORE-CHECKS ! 0 CORE-FAILURES ! 0 CORE-DONE !
: CORE-ASSERT
  1 CORE-CHECKS +! 0= IF
    CORE-CHECKS @ CORE-ERRORS CORE-FAILURES @ 6 * + DUP >R !
    CORE-ACTUAL @ R@ 2 + ! CORE-EXPECTED @ R> 4 + !
    1 CORE-FAILURES +!
  THEN
;
: CORE-= DUP CORE-EXPECTED ! OVER CORE-ACTUAL ! = CORE-ASSERT ;
BANK@ CONSTANT CORE-BANK
: CORE-PAGE BANK@ ;
: CORE-THROW 99 THROW ;
: CORE-INNER BANK@ 8 CORE-= ;
: CORE-OUTER
  ['] CORE-INNER 8 WITH-PAGE 0 CORE-=
  BANK@ 9 CORE-=
;
' CORE-PAGE 8 WITH-PAGE 0 CORE-= 8 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-PAGE 63 WITH-PAGE 0 CORE-= 63 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-THROW 8 WITH-PAGE 99 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-PAGE 64 WITH-PAGE 10 CORE-=
' CORE-PAGE 65535 WITH-PAGE 10 CORE-=
BANK@ CORE-BANK CORE-=
' CORE-OUTER 9 WITH-PAGE 0 CORE-=
BANK@ CORE-BANK CORE-=
16384 FS-BUF 1 STORAGE-READ 10 CORE-=
65535 FS-BUF 0 STORAGE-READ 10 CORE-=
0 33791 1 STORAGE-READ 10 CORE-=
0 65535 1 STORAGE-READ 10 CORE-=
0 SERVICE@ ' PAGE CORE-=
4 SERVICE@ ' YIELD CORE-=
15 SERVICE@ 0 CORE-=
65535 SERVICE@ 0 CORE-=
UNUSED 3 OS-CALL CORE-=
: CORE-BAD-CALL 15 OS-CALL ;
' CORE-BAD-CALL CATCH 20 CORE-=
: CORE-EVAL-OK S" 2 3 +" DROP EVALUATE0 ;
: CORE-EVAL-BASE S" HEX 17" DROP EVALUATE0 ;
: CORE-EVAL-BAD S" 42 NO-SUCH-CORE-WORD" DROP EVALUATE0 ;
: CORE-EVAL-THROW S" HEX 42 88 THROW" DROP EVALUATE0 ;
: CORE-EVAL-NEST S" CORE-EVAL-OK" DROP EVALUATE0 ;
: CORE-EVAL-LONG S" AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" DROP EVALUATE0 ;
: CORE-EVAL-MAX S" : AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 17 ; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" DROP EVALUATE0 ;
123 CORE-EVAL-OK 0 CORE-= 5 CORE-= 123 CORE-=
\ Numeric input is currently decimal even when BASE changes for output.
CORE-EVAL-BASE 0 CORE-= 17 CORE-= BASE @ 10 CORE-=
CORE-EVAL-BAD 1 CORE-= 42 CORE-=
123 CORE-EVAL-THROW 88 CORE-= 123 CORE-=
BASE @ 10 CORE-=
CORE-EVAL-NEST 0 CORE-= 0 CORE-= 5 CORE-=
CORE-EVAL-LONG 19 CORE-=
WORD-BUF 31 + C@ 0 CORE-=
CORE-EVAL-OK 0 CORE-= 5 CORE-=
CORE-EVAL-MAX 0 CORE-= 17 CORE-=
CORE-EVAL-LONG 19 CORE-=
CORE-EVAL-OK 0 CORE-= 5 CORE-=
: CORE-INPUT-CHECK
  INPUT-PTR @ >R CORE-EVAL-OK 2DROP INPUT-PTR @ R> =
;
CORE-INPUT-CHECK 1 CORE-=
\ Failed/unfinished source must not strand the caller in a hidden definition.
: CORE-BAD-DEFINITION S" : CORE-PARTIAL NO-SUCH-CORE-WORD" DROP EVALUATE0 ;
: CORE-UNFINISHED S" : CORE-PARTIAL 17" DROP EVALUATE0 ;
: CORE-COMPILE-THROW 88 THROW ; IMMEDIATE
: CORE-THROWN-PARTIAL S" : CORE-PARTIAL CORE-COMPILE-THROW" DROP EVALUATE0 ;
: CORE-CHECK-BAD
  HERE >R LATEST @ >R
  CORE-BAD-DEFINITION 1 CORE-=
  STATE @ 0 CORE-= LATEST @ R> CORE-= HERE R> CORE-=
;
: CORE-CHECK-UNFINISHED
  HERE >R LATEST @ >R
  CORE-UNFINISHED 22 CORE-=
  STATE @ 0 CORE-= LATEST @ R> CORE-= HERE R> CORE-=
;
: CORE-CHECK-THROWN
  HERE >R LATEST @ >R
  CORE-THROWN-PARTIAL 88 CORE-=
  STATE @ 0 CORE-= LATEST @ R> CORE-= HERE R> CORE-=
;
CORE-CHECK-BAD CORE-CHECK-UNFINISHED CORE-CHECK-THROWN
CORE-EVAL-OK 0 CORE-= 5 CORE-=
: CORE-STORE-BAD
  S" : CORE-FILEPART NOPE" S" CORE/BAD" 2 FS-PUT 0 CORE-=
;
: CORE-STORE-UNFINISHED
  S" : CORE-FILEPART 17" S" CORE/BAD" 2 FS-PUT 0 CORE-=
;
: CORE-CHECK-FILE ( expected-ior -- )
  >R HERE >R LATEST @ >R
  S" CORE/BAD" FS-LOAD
  STATE @ 0 CORE-= FS-BUSY @ 0 CORE-=
  LATEST @ R> CORE-= HERE R> CORE-= R> CORE-=
;
CORE-STORE-BAD 1 CORE-CHECK-FILE
CORE-STORE-UNFINISHED 22 CORE-CHECK-FILE
CORE-EVAL-OK 0 CORE-= 5 CORE-=
\ Immediate clients may evaluate in compilation state if it stays balanced.
: CORE-INJECT S" 23" DROP EVALUATE0 0 CORE-= ; IMMEDIATE
: CORE-COMPILED CORE-INJECT ;
CORE-COMPILED 23 CORE-=
: CORE-BREAK-STATE S" [" DROP EVALUATE0 22 CORE-= ; IMMEDIATE
: CORE-BALANCED CORE-BREAK-STATE 24 ;
CORE-BALANCED 24 CORE-=
: CORE-INJECT-THROW S" CORE-COMPILE-THROW" DROP EVALUATE0 88 CORE-= ; IMMEDIATE
: CORE-AFTER-THROW CORE-INJECT-THROW 25 ;
CORE-AFTER-THROW 25 CORE-=
51966 CORE-DONE !
