\ Dictionary bounds and distinct fixed RAM above C000, on a disposable ROM.
VARIABLE MEM-CHECKS VARIABLE MEM-FAILURES VARIABLE MEM-DONE
VARIABLE MEM-DP VARIABLE MEM-LATEST
0 MEM-CHECKS ! 0 MEM-FAILURES ! 0 MEM-DONE !
: MEM-ASSERT 1 MEM-CHECKS +! 0= IF 1 MEM-FAILURES +! THEN ;
: MEM-= = MEM-ASSERT ;
: MEM-GROW 1 ALLOT ;
: MEM-SHRINK 0 1 - ALLOT ;
: MEM-HUGE 32768 ALLOT ;
: MEM-NOOP 0 ALLOT ;
: MEM-CELL 4660 , ;
: MEM-BYTE 90 C, ;
: MEM-ROOM 65535 ROOM ;
: MEM-CREATE S" CREATE ZZ" DROP EVALUATE0 ;
: MEM-CREATE-MISSING S" CREATE" DROP EVALUATE0 ;
: MEM-COLON-MISSING S" :" DROP EVALUATE0 ;
: MEM-RESTORE MEM-LATEST @ LATEST ! MEM-DP @ DP ! ;
: MEM-SAME-LATEST LATEST @ MEM-LATEST @ MEM-= ;
: MEM-MAIN
  DEPTH >R
  HERE MEM-DP ! LATEST @ MEM-LATEST !
  DP-LIMIT 57344 MEM-=
  USED UNUSED + H0 + DP-LIMIT MEM-=
  MEM-CREATE-MISSING 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  MEM-COLON-MISSING 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  BANK@ >R
  64 MAP-FLASH 0 MEM-= BANK@ R@ MEM-=
  256 MAP-FLASH 0 MEM-= BANK@ R@ MEM-=
  8 MAP-FLASH 1 MEM-= BANK@ 63 AND 8 MEM-=
  R> (BANK!)

  \ C000 must not alias the scratch byte at 8000.
  32768 C@ >R 49152 C@ >R
  165 32768 C! 90 49152 C!
  32768 C@ 165 MEM-= 49152 C@ 90 MEM-=
  R> 49152 C! R> 32768 C!

  49152 DP ! MEM-CELL MEM-CELL
  HERE 49156 MEM-=
  49152 @ 4660 MEM-= 49154 @ 4660 MEM-=
  UNUSED DP-LIMIT 49156 - MEM-=
  USED UNUSED + H0 + DP-LIMIT MEM-=
  MEM-RESTORE

  \ Protect a byte outside the dictionary while probing exact-fit writes.
  DP-LIMIT C@ >R 165 DP-LIMIT C!
  DP-LIMIT 1- C@ >R
  DP-LIMIT 1- DP ! 77 HERE C!
  123 ['] MEM-CELL CATCH 8 MEM-= 123 MEM-=
  HERE DP-LIMIT 1- MEM-= HERE C@ 77 MEM-=
  DP-LIMIT C@ 165 MEM-= MEM-SAME-LATEST
  MEM-BYTE HERE DP-LIMIT MEM-=
  DP-LIMIT 1- C@ 90 MEM-=
  ['] MEM-BYTE CATCH 8 MEM-=
  ['] MEM-CELL CATCH 8 MEM-=
  ['] MEM-GROW CATCH 8 MEM-=
  ['] MEM-NOOP CATCH 0 MEM-=
  HERE DP-LIMIT MEM-= MEM-SAME-LATEST
  DP-LIMIT 2 - DP ! MEM-CELL
  HERE DP-LIMIT MEM-= DP-LIMIT 2 - @ 4660 MEM-=
  DP-LIMIT C@ 165 MEM-=

  \ CREATE reserves link/flags/name/NUL/CALL before changing LATEST.
  DP-LIMIT 8 - DP !
  MEM-CREATE 8 MEM-=
  HERE DP-LIMIT 8 - MEM-= MEM-SAME-LATEST
  DP-LIMIT 9 - DP !
  MEM-CREATE 0 MEM-=
  HERE DP-LIMIT MEM-=
  LATEST @ DP-LIMIT 9 - MEM-=
  MEM-LATEST @ LATEST !

  \ DOES> emits five bytes and must reject a four-byte remainder.
  DP-LIMIT 4 - DP ! 77 HERE C!
  ['] DOES> CATCH 8 MEM-=
  HERE DP-LIMIT 4 - MEM-= HERE C@ 77 MEM-=
  MEM-SAME-LATEST DP-LIMIT C@ 165 MEM-=
  R> DP-LIMIT 1- C! R> DP-LIMIT C!
  MEM-RESTORE

  16 ALLOT HERE MEM-DP @ 16 + MEM-=
  0 16 - ALLOT HERE MEM-DP @ MEM-=
  H0 DP ! ['] MEM-SHRINK CATCH 8 MEM-=
  HERE H0 MEM-=
  H0 1- DP ! ['] MEM-NOOP CATCH 8 MEM-=
  HERE H0 1- MEM-=
  DP-LIMIT 1+ DP ! ['] MEM-NOOP CATCH 8 MEM-=
  HERE DP-LIMIT 1+ MEM-=
  MEM-RESTORE
  ['] MEM-HUGE CATCH 8 MEM-=
  ['] MEM-ROOM CATCH 8 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  DEPTH R> MEM-=
  51966 MEM-DONE !
;
MEM-MAIN
