\ Dictionary bounds and distinct fixed RAM above C000, on a disposable ROM.
VARIABLE MEM-CHECKS VARIABLE MEM-FAILURES VARIABLE MEM-DONE
VARIABLE MEM-DP VARIABLE MEM-LATEST
0 MEM-CHECKS ! 0 MEM-FAILURES ! 0 MEM-DONE !
: MEM-ASSERT 1 MEM-CHECKS +! 0= IF 1 MEM-FAILURES +! THEN ;
: MEM-= = MEM-ASSERT ;
: MEM-GROW 1 ALLOT ;
: MEM-SHRINK 0 1 - ALLOT ;
: MEM-HUGE 32768 ALLOT ;
: MEM-NOOP 0 ALLOT ;
: MEM-CELL 4660 , ;
: MEM-BYTE 90 C, ;
: MEM-ROOM 65535 ROOM ;
: MEM-CREATE S" CREATE ZZ" DROP EVALUATE0 ;
: MEM-CREATE-MISSING S" CREATE" DROP EVALUATE0 ;
: MEM-COLON-MISSING S" :" DROP EVALUATE0 ;
: MEM-RESTORE MEM-LATEST @ LATEST ! MEM-DP @ DP ! ;
: MEM-SAME-LATEST LATEST @ MEM-LATEST @ MEM-= ;

\ Byte-built sources deliberately contain an early EOF before a closing quote.
HERE 83 C, 34 C, 32 C, 88 C, 34 C, 0 C, CONSTANT MEM-STRING-SOURCE
HERE 83 C, 34 C, 32 C, 34 C, 0 C, CONSTANT MEM-EMPTY-SOURCE
HERE 83 C, 34 C, 32 C, 65 C, 0 C, 66 C, 34 C, 0 C, CONSTANT MEM-BAD-STRING
HERE 46 C, 34 C, 32 C, 65 C, 0 C, 66 C, 34 C, 0 C, CONSTANT MEM-BAD-DOT
HERE 58 C, 32 C, 77 C, 69 C, 77 C, 45 C, 80 C, 65 C, 82 C, 84 C, 32 C, 83 C, 34 C, 32 C, 65 C, 0 C, 66 C, 34 C, 32 C, 59 C, 0 C, CONSTANT MEM-BAD-COMPILED

: MEM-STRING
  MEM-STRING-SOURCE EVALUATE0 DUP 0= IF DROP 2DROP 0 THEN ;
: MEM-BAD-QUOTE
  MEM-BAD-STRING EVALUATE0 DUP 0= IF DROP 2DROP 0 THEN ;
: MEM-COMPILE-STRING
  INPUT-PTR @ >R STATE @ >R
  MEM-STRING-SOURCE 3 + INPUT-PTR ! 1 STATE !
  ['] S" CATCH R> STATE ! R> INPUT-PTR ! ;
: MEM-PARSE-CHECKS
  MEM-BAD-QUOTE 18 MEM-=
  MEM-BAD-DOT EVALUATE0 18 MEM-=
  MEM-BAD-COMPILED EVALUATE0 18 MEM-=
  MEM-RESTORE
  77 HERE C! 77 HERE 1+ C!
  MEM-STRING-SOURCE EVALUATE0 0 MEM-=
  1 MEM-= DUP HERE MEM-= DUP C@ 88 MEM-= 1+ C@ 0 MEM-=
  MEM-EMPTY-SOURCE EVALUATE0 0 MEM-=
  0 MEM-= C@ 0 MEM-=
  HERE MEM-DP @ MEM-=
  DP-LIMIT C@ >R DP-LIMIT 1+ C@ >R
  165 DP-LIMIT C! 90 DP-LIMIT 1+ C!
  DP-LIMIT DP ! MEM-STRING 8 MEM-=
  HERE DP-LIMIT MEM-= DP-LIMIT C@ 165 MEM-=
  DP-LIMIT 1+ C@ 90 MEM-=
  R> DP-LIMIT 1+ C! R> DP-LIMIT C!
  DP-LIMIT 5 - DP ! 77 HERE C!
  MEM-COMPILE-STRING 8 MEM-=
  HERE DP-LIMIT 5 - MEM-= HERE C@ 77 MEM-= MEM-SAME-LATEST
  DP-LIMIT 6 - DP ! MEM-COMPILE-STRING 0 MEM-=
  HERE DP-LIMIT MEM-= DP-LIMIT 2 - C@ 88 MEM-=
  DP-LIMIT 1- C@ 0 MEM-= MEM-SAME-LATEST
  MEM-RESTORE
;


: MEM-VARIABLE S" VARIABLE ZZ" DROP EVALUATE0 ;
: MEM-CONSTANT S" 7 CONSTANT ZZ" DROP EVALUATE0 ;
: MEM-NAME-CHECKS
  S" '" DROP EVALUATE0 16 MEM-=
  S" ' MEM-UNKNOWN" DROP EVALUATE0 1 MEM-=
  S" CHAR" DROP EVALUATE0 16 MEM-=
  S" TO" DROP EVALUATE0 16 MEM-=
  S" TO MEM-UNKNOWN" DROP EVALUATE0 1 MEM-=
  S" +TO MEM-UNKNOWN" DROP EVALUATE0 1 MEM-=
  S" FORGET MEM-UNKNOWN" DROP EVALUATE0 1 MEM-=
  S" : NN [CHAR]" DROP EVALUATE0 16 MEM-=
  S" : NN ['] MEM-UNKNOWN ;" DROP EVALUATE0 1 MEM-=
  S" : NN POSTPONE MEM-UNKNOWN ;" DROP EVALUATE0 1 MEM-=
  S" VARIABLE" DROP EVALUATE0 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  S" 7 CONSTANT" DROP EVALUATE0 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  DP-LIMIT 16 - DP ! MEM-VARIABLE 8 MEM-=
  HERE DP-LIMIT 16 - MEM-= MEM-SAME-LATEST
  DP-LIMIT 17 - DP ! MEM-VARIABLE 0 MEM-=
  HERE DP-LIMIT MEM-= MEM-RESTORE
  DP-LIMIT 14 - DP ! MEM-CONSTANT 8 MEM-=
  HERE DP-LIMIT 14 - MEM-= MEM-SAME-LATEST
  DP-LIMIT 15 - DP ! MEM-CONSTANT 0 MEM-=
  HERE DP-LIMIT MEM-= MEM-RESTORE
;

: MEM-MAIN
  DEPTH >R
  HERE MEM-DP ! LATEST @ MEM-LATEST !
  MEM-PARSE-CHECKS MEM-NAME-CHECKS
  DP-LIMIT 57344 MEM-=
  USED UNUSED + H0 + DP-LIMIT MEM-=
  MEM-CREATE-MISSING 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  MEM-COLON-MISSING 16 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  BANK@ >R
  64 MAP-FLASH 0 MEM-= BANK@ R@ MEM-=
  256 MAP-FLASH 0 MEM-= BANK@ R@ MEM-=
  8 MAP-FLASH 1 MEM-= BANK@ 63 AND 8 MEM-=
  R> (BANK!)

  \ Probe equal offsets in the two fixed RAM windows, away from test code.
  \ Restore both bytes before calling any resident or assertion words.
  40704 C@ >R 57088 C@ >R
  165 40704 C! 90 57088 C!
  40704 C@ 57088 C@
  R> 57088 C! R> 40704 C!
  90 MEM-= 165 MEM-=

  \ The fixture can grow past C000; allocation probes must not overwrite it.
  DP-LIMIT 128 - DP ! MEM-CELL MEM-CELL
  HERE DP-LIMIT 124 - MEM-=
  DP-LIMIT 128 - @ 4660 MEM-= DP-LIMIT 126 - @ 4660 MEM-=
  UNUSED 124 MEM-=
  USED UNUSED + H0 + DP-LIMIT MEM-=
  MEM-RESTORE

  \ Protect a byte outside the dictionary while probing exact-fit writes.
  DP-LIMIT C@ >R 165 DP-LIMIT C!
  DP-LIMIT 1- C@ >R
  DP-LIMIT 1- DP ! 77 HERE C!
  123 ['] MEM-CELL CATCH 8 MEM-= 123 MEM-=
  HERE DP-LIMIT 1- MEM-= HERE C@ 77 MEM-=
  DP-LIMIT C@ 165 MEM-= MEM-SAME-LATEST
  MEM-BYTE HERE DP-LIMIT MEM-=
  DP-LIMIT 1- C@ 90 MEM-=
  ['] MEM-BYTE CATCH 8 MEM-=
  ['] MEM-CELL CATCH 8 MEM-=
  ['] MEM-GROW CATCH 8 MEM-=
  ['] MEM-NOOP CATCH 0 MEM-=
  HERE DP-LIMIT MEM-= MEM-SAME-LATEST
  DP-LIMIT 2 - DP ! MEM-CELL
  HERE DP-LIMIT MEM-= DP-LIMIT 2 - @ 4660 MEM-=
  DP-LIMIT C@ 165 MEM-=

  \ CREATE reserves link/flags/name/NUL/CALL before changing LATEST.
  DP-LIMIT 8 - DP !
  MEM-CREATE 8 MEM-=
  HERE DP-LIMIT 8 - MEM-= MEM-SAME-LATEST
  DP-LIMIT 9 - DP !
  MEM-CREATE 0 MEM-=
  HERE DP-LIMIT MEM-=
  LATEST @ DP-LIMIT 9 - MEM-=
  MEM-LATEST @ LATEST !

  \ DOES> emits five bytes and must reject a four-byte remainder.
  DP-LIMIT 4 - DP ! 77 HERE C!
  ['] DOES> CATCH 8 MEM-=
  HERE DP-LIMIT 4 - MEM-= HERE C@ 77 MEM-=
  MEM-SAME-LATEST DP-LIMIT C@ 165 MEM-=
  R> DP-LIMIT 1- C! R> DP-LIMIT C!
  MEM-RESTORE

  16 ALLOT HERE MEM-DP @ 16 + MEM-=
  0 16 - ALLOT HERE MEM-DP @ MEM-=
  H0 DP ! ['] MEM-SHRINK CATCH 8 MEM-=
  HERE H0 MEM-=
  H0 1- DP ! ['] MEM-NOOP CATCH 8 MEM-=
  HERE H0 1- MEM-=
  DP-LIMIT 1+ DP ! ['] MEM-NOOP CATCH 8 MEM-=
  HERE DP-LIMIT 1+ MEM-=
  MEM-RESTORE
  ['] MEM-HUGE CATCH 8 MEM-=
  ['] MEM-ROOM CATCH 8 MEM-=
  HERE MEM-DP @ MEM-= MEM-SAME-LATEST
  DEPTH R> MEM-=
  51966 MEM-DONE !
;
MEM-MAIN
