\ Run once against a disposable ROM with an erased storage page.
\ Leaves FS-TEST-FAILURES and FS-TEST-CHECKS for emulator assertions.
VARIABLE FS-TEST-FAILURES
VARIABLE FS-TEST-CHECKS
VARIABLE FS-TEST-VALUE
VARIABLE FS-TEST-START-FREE
0 FS-TEST-FAILURES ! 0 FS-TEST-CHECKS !
: FS-ASSERT ( flag -- )
  1 FS-TEST-CHECKS +! 0= IF 1 FS-TEST-FAILURES +! THEN ;
: FS-EXPECT-MISSING ( name len -- )
  FS-GET 43 = FS-ASSERT 0= FS-ASSERT 0= FS-ASSERT 0= FS-ASSERT ;
: FS-STORAGE-TEST
  FS-FREE FS-TEST-START-FREE !
  FS-COUNT 0= FS-ASSERT
  FS-FREE 16 = FS-ASSERT
  S" TEST/MISSING" FS-EXPECT-MISSING
  0 0 0 0 1 FS-PUT 40 = FS-ASSERT
  0 0 0 17 1 FS-PUT 40 = FS-ASSERT
  0 0 0 65535 1 FS-PUT 40 = FS-ASSERT
  0 0 S" TEST/BAD" 4 FS-PUT 41 = FS-ASSERT
  0 0 S" TEST/BAD" 65535 FS-PUT 41 = FS-ASSERT
  0 993 S" TEST/BAD" 1 FS-PUT 41 = FS-ASSERT
  0 65535 S" TEST/BAD" 1 FS-PUT 41 = FS-ASSERT
  0 992 S" TEST/BAD" 2 FS-PUT 41 = FS-ASSERT
  FS-FREE FS-TEST-START-FREE @ = FS-ASSERT
  1 FS-BUSY !
  0 0 S" TEST/BUSY" 1 FS-PUT 45 = FS-ASSERT
  S" TEST/BUSY" FS-DELETE 45 = FS-ASSERT
  S" TEST/BUSY" FS-GET 45 = FS-ASSERT DROP 2DROP
  S" TEST/BUSY" FS-LOAD 45 = FS-ASSERT
  0 FS-BUSY !

  S" FIRST" S" TEST/A" 1 FS-PUT 0= FS-ASSERT
  FS-COUNT 1 = FS-ASSERT
  S" TEST/A" FS-GET 0= FS-ASSERT 1 = FS-ASSERT
  5 = FS-ASSERT C@ 70 = FS-ASSERT
  S" NEXT" S" TEST/A" 1 FS-PUT 0= FS-ASSERT
  FS-COUNT 1 = FS-ASSERT
  S" TEST/A" FS-GET 0= FS-ASSERT 1 = FS-ASSERT
  4 = FS-ASSERT C@ 78 = FS-ASSERT

  \ Saving a pointer returned by GET must survive directory scans.
  S" TEST/A" FS-GET DROP DROP S" TEST/B" 3 FS-PUT 0= FS-ASSERT
  S" TEST/B" FS-GET 0= FS-ASSERT 3 = FS-ASSERT
  4 = FS-ASSERT C@ 78 = FS-ASSERT
  S" TEST/B" FS-LOAD 41 = FS-ASSERT
  FS-COUNT 2 = FS-ASSERT
  0 FS-NTH 1 = FS-ASSERT DROP DROP 6 = FS-ASSERT C@ 84 = FS-ASSERT
  2 FS-NTH 0= FS-ASSERT DROP DROP 2DROP
  65535 FS-NTH 0= FS-ASSERT DROP DROP 2DROP

  S" TEST/A" FS-DELETE 0= FS-ASSERT
  S" TEST/A" FS-EXPECT-MISSING
  S" TEST/A" FS-DELETE 43 = FS-ASSERT
  FS-COUNT 1 = FS-ASSERT
  0 0 S" TEST/EMPTY" 1 FS-PUT 0= FS-ASSERT
  S" TEST/EMPTY" FS-GET 0= FS-ASSERT 1 = FS-ASSERT
  0= FS-ASSERT DROP
  0 FS-TEST-VALUE !
  S" 123 FS-TEST-VALUE !" S" TEST/SOURCE" 2 FS-PUT 0= FS-ASSERT
  S" TEST/SOURCE" FS-LOAD 0= FS-ASSERT
  FS-TEST-VALUE @ 123 = FS-ASSERT

  \ An interrupted record consumes space but never appears in the directory.
  FS-COMMIT 14337 1 STORAGE-WRITE 0= FS-ASSERT
  FS-COUNT 3 = FS-ASSERT
  FS-FREE FS-TEST-START-FREE @ 7 - = FS-ASSERT
;
\ Optional capacity check; run only after the normal test on a throwaway ROM.
: FS-STORAGE-FULL-TEST
  BEGIN FS-FREE WHILE
    0 0 S" TEST/FULL" 1 FS-PUT 0= FS-ASSERT
  REPEAT
  0 0 S" TEST/FULL" 1 FS-PUT 42 = FS-ASSERT
  S" TEST/B" FS-GET 0= FS-ASSERT 3 = FS-ASSERT
  4 = FS-ASSERT C@ 78 = FS-ASSERT
;
FS-STORAGE-TEST
