\ Append after the resident task source and the T{ test harness.
\ This file does not require idle dispatch: every scheduling pass is explicit.
TASK-INIT
VARIABLE TASK-TEST-A
VARIABLE TASK-TEST-B
: TASK-TEST-INC ( addr -- ) 1 SWAP +! ;
: TASK-TEST-FAIL ( context -- ) DROP 0 99 - THROW ;
: TASK-TEST-LEAK ( context -- ) DROP 42 ;
: TASK-TEST-REENTER ( addr -- ) YIELD 1 SWAP +! ;
: TASK-TEST-SLEEP ( addr -- ) 1 SWAP +! 2 TASK-ID TASK-SLEEP DROP ;
0 TASK-TEST-A ! 0 TASK-TEST-B !
T{ 0 0 TASK-NEW -> 0 }T
T{ ' TASK-TEST-INC TASK-TEST-A TASK-NEW -> 1 }T
T{ ' TASK-TEST-INC TASK-TEST-B TASK-NEW -> 2 }T
T{ YIELD TASK-TEST-A @ TASK-TEST-B @ -> 1 1 }T
T{ 1 TASK-INFO -> 1 1 0 }T
T{ 1 TASK-PAUSE YIELD TASK-TEST-A @ TASK-TEST-B @ -> 1 1 2 }T
T{ 1 TASK-RUN YIELD TASK-TEST-A @ TASK-TEST-B @ -> 1 2 3 }T
T{ 2 TASK-STOP YIELD TASK-TEST-B @ -> 1 3 }T
T{ 2 TASK-INFO -> 3 3 0 }T
T{ 0 TASK-RUN 5 TASK-RUN 65535 TASK-FREE -> 0 0 0 }T
T{ 2 TASK-FREE 2 TASK-INFO -> 1 0 0 0 }T
T{ ' TASK-TEST-FAIL 0 TASK-NEW -> 2 }T
T{ YIELD 2 TASK-INFO -> 4 1 0 99 - }T
T{ 123 YIELD -> 123 }T
T{ 2 TASK-FREE ' TASK-TEST-LEAK 0 TASK-NEW -> 1 2 }T
T{ 123 YIELD 2 TASK-INFO -> 123 4 1 0 4 - }T
T{ 2 TASK-FREE ' TASK-TEST-REENTER TASK-TEST-B TASK-NEW -> 1 2 }T
T{ YIELD TASK-TEST-B @ -> 4 }T
T{ ' TASK-TEST-INC TASK-TEST-B TASK-NEW -> 3 }T
T{ ' TASK-TEST-INC TASK-TEST-B TASK-NEW -> 4 }T
T{ ' TASK-TEST-INC TASK-TEST-B TASK-NEW -> 0 }T
TASK-INIT
0 TASK-TEST-A !
T{ ' TASK-TEST-SLEEP TASK-TEST-A TASK-NEW -> 1 }T
T{ YIELD 1 TASK-INFO -> 5 1 0 }T
T{ YIELD YIELD TASK-TEST-A @ -> 1 }T
T{ YIELD TASK-TEST-A @ -> 2 }T
T{ 0 1 TASK-SLEEP 1 TASK-INFO -> 1 1 2 0 }T
TASK-INIT
