\ Load with EVALUATE0 after resident os-tasks.fs. No external test harness.
VARIABLE TASK-TESTS
VARIABLE TASK-FAILURES
0 TASK-TESTS ! 0 TASK-FAILURES !
: TASK-ASSERT ( flag -- )
  1 TASK-TESTS +! 0= IF 1 TASK-FAILURES +! THEN
;
: TASK-ASSERT= ( actual expected -- ) = TASK-ASSERT ;
VARIABLE TASK-A
VARIABLE TASK-B
: TASK-INC ( addr -- ) 1 SWAP +! ;
: TASK-FAIL ( context -- ) DROP 0 99 - THROW ;
: TASK-LEAK ( context -- ) DROP 42 ;
: TASK-REENTER ( addr -- ) YIELD 1 SWAP +! ;
: TASK-WAIT ( addr -- ) 1 SWAP +! 2 TASK-ID TASK-SLEEP DROP ;
: TASK-SELF-FREE ( addr -- ) DROP TASK-ID TASK-FREE IF 0 98 - THROW THEN ;
: TASK-CHANGE-BASE ( addr -- ) DROP HEX 0 99 - THROW ;
VARIABLE TASK-SAVED-BANK
: TASK-CHANGE-BANK ( context -- ) DROP 63 MAP-FLASH DROP ;
: TASK-BANK-FAIL ( context -- ) TASK-CHANGE-BANK 0 98 - THROW ;

TASK-INIT
0 TASK-A ! 0 TASK-B !
0 0 TASK-NEW 0 TASK-ASSERT=
' TASK-INC TASK-A TASK-NEW 1 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 2 TASK-ASSERT=
YIELD TASK-A @ 1 TASK-ASSERT= TASK-B @ 1 TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
1 TASK-PAUSE TASK-ASSERT
YIELD TASK-A @ 1 TASK-ASSERT= TASK-B @ 2 TASK-ASSERT=
1 TASK-RUN TASK-ASSERT
YIELD TASK-A @ 2 TASK-ASSERT= TASK-B @ 3 TASK-ASSERT=
2 TASK-STOP TASK-ASSERT
YIELD TASK-B @ 3 TASK-ASSERT=
2 TASK-INFO 0 TASK-ASSERT= 3 TASK-ASSERT= 3 TASK-ASSERT=
0 TASK-RUN 0 TASK-ASSERT=
5 TASK-RUN 0 TASK-ASSERT=
65535 TASK-FREE 0 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
2 TASK-INFO 0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
' TASK-FAIL 0 TASK-NEW 2 TASK-ASSERT=
YIELD 2 TASK-INFO 0 99 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
123 YIELD 123 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
' TASK-LEAK 0 TASK-NEW 2 TASK-ASSERT=
123 YIELD 2 TASK-INFO 0 4 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
123 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
' TASK-REENTER TASK-B TASK-NEW 2 TASK-ASSERT=
YIELD TASK-B @ 4 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 3 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 4 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 0 TASK-ASSERT=
TASK-INIT
0 TASK-A !
' TASK-WAIT TASK-A TASK-NEW 1 TASK-ASSERT=
YIELD 1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 5 TASK-ASSERT=
YIELD YIELD TASK-A @ 1 TASK-ASSERT=
YIELD TASK-A @ 2 TASK-ASSERT=
0 1 TASK-SLEEP TASK-ASSERT
1 TASK-INFO 0 TASK-ASSERT= 2 TASK-ASSERT= 1 TASK-ASSERT=
TASK-INIT
' TASK-SELF-FREE 0 TASK-NEW 1 TASK-ASSERT=
YIELD 1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
TASK-BUSY @ 0 TASK-ASSERT=
TASK-ID 0 TASK-ASSERT=
TASK-INIT
' TASK-CHANGE-BASE 0 TASK-NEW 1 TASK-ASSERT=
YIELD BASE @ 10 TASK-ASSERT=
1 TASK-INFO 0 99 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
TASK-INIT
\ A callback may map flash while it runs, including before throwing. The
\ interpreter's source and subsequent callbacks must see the original bank.
BANK@ TASK-SAVED-BANK !
' TASK-CHANGE-BANK 0 TASK-NEW 1 TASK-ASSERT=
YIELD BANK@ TASK-SAVED-BANK @ TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
1 TASK-FREE TASK-ASSERT
' TASK-BANK-FAIL 0 TASK-NEW 1 TASK-ASSERT=
YIELD BANK@ TASK-SAVED-BANK @ TASK-ASSERT=
1 TASK-INFO 0 98 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
TASK-INIT
TASK-FAILURES @ . ." task failures / " TASK-TESTS @ . CR
