\ Load after the resident modules, including the shell. No external harness.
VARIABLE TASK-TESTS
VARIABLE TASK-FAILURES
0 TASK-TESTS ! 0 TASK-FAILURES !
: TASK-ASSERT ( flag -- )
  1 TASK-TESTS +! 0= IF 1 TASK-FAILURES +! THEN
;
: TASK-ASSERT= ( actual expected -- ) = TASK-ASSERT ;
VARIABLE TASK-A
VARIABLE TASK-B
: TASK-INC ( addr -- ) 1 SWAP +! ;
: TASK-FAIL ( context -- ) DROP 0 99 - THROW ;
: TASK-LEAK ( context -- ) DROP 42 ;
: TASK-REENTER ( addr -- ) YIELD 1 SWAP +! ;
: TASK-WAIT ( addr -- ) 1 SWAP +! 2 TASK-ID TASK-SLEEP DROP ;
: TASK-SELF-FREE ( addr -- ) DROP TASK-ID TASK-FREE IF 0 98 - THROW THEN ;
: TASK-CHANGE-BASE ( addr -- ) DROP HEX 0 99 - THROW ;
VARIABLE TASK-SAVED-BANK
: TASK-CHANGE-BANK ( context -- ) DROP 63 MAP-FLASH DROP ;
: TASK-BANK-FAIL ( context -- ) TASK-CHANGE-BANK 0 98 - THROW ;

TASK-INIT
0 TASK-A ! 0 TASK-B !
0 0 TASK-NEW 0 TASK-ASSERT=
' TASK-INC TASK-A TASK-NEW 1 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 2 TASK-ASSERT=
YIELD TASK-A @ 1 TASK-ASSERT= TASK-B @ 1 TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
1 TASK-PAUSE TASK-ASSERT
YIELD TASK-A @ 1 TASK-ASSERT= TASK-B @ 2 TASK-ASSERT=
1 TASK-RUN TASK-ASSERT
YIELD TASK-A @ 2 TASK-ASSERT= TASK-B @ 3 TASK-ASSERT=
2 TASK-STOP TASK-ASSERT
YIELD TASK-B @ 3 TASK-ASSERT=
2 TASK-INFO 0 TASK-ASSERT= 3 TASK-ASSERT= 3 TASK-ASSERT=
0 TASK-RUN 0 TASK-ASSERT=
5 TASK-RUN 0 TASK-ASSERT=
65535 TASK-FREE 0 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
2 TASK-INFO 0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
' TASK-FAIL 0 TASK-NEW 2 TASK-ASSERT=
YIELD 2 TASK-INFO 0 99 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
123 YIELD 123 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
' TASK-LEAK 0 TASK-NEW 2 TASK-ASSERT=
123 YIELD 2 TASK-INFO 0 4 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
123 TASK-ASSERT=
2 TASK-FREE TASK-ASSERT
' TASK-REENTER TASK-B TASK-NEW 2 TASK-ASSERT=
YIELD TASK-B @ 4 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 3 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 4 TASK-ASSERT=
' TASK-INC TASK-B TASK-NEW 0 TASK-ASSERT=
TASK-INIT
0 TASK-A !
' TASK-WAIT TASK-A TASK-NEW 1 TASK-ASSERT=
YIELD 1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 5 TASK-ASSERT=
YIELD YIELD TASK-A @ 1 TASK-ASSERT=
YIELD TASK-A @ 2 TASK-ASSERT=
0 1 TASK-SLEEP TASK-ASSERT
1 TASK-INFO 0 TASK-ASSERT= 2 TASK-ASSERT= 1 TASK-ASSERT=
TASK-INIT
' TASK-SELF-FREE 0 TASK-NEW 1 TASK-ASSERT=
YIELD 1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
TASK-BUSY @ 0 TASK-ASSERT=
TASK-ID 0 TASK-ASSERT=
TASK-INIT
' TASK-CHANGE-BASE 0 TASK-NEW 1 TASK-ASSERT=
YIELD BASE @ 10 TASK-ASSERT=
1 TASK-INFO 0 99 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
TASK-INIT
\ A callback may map flash while it runs, including before throwing. The
\ interpreter's source and subsequent callbacks must see the original bank.
BANK@ TASK-SAVED-BANK !
' TASK-CHANGE-BANK 0 TASK-NEW 1 TASK-ASSERT=
YIELD BANK@ TASK-SAVED-BANK @ TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
1 TASK-FREE TASK-ASSERT
' TASK-BANK-FAIL 0 TASK-NEW 1 TASK-ASSERT=
YIELD BANK@ TASK-SAVED-BANK @ TASK-ASSERT=
1 TASK-INFO 0 98 - TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
TASK-INIT
\ A callback's complete SOURCE/>IN state is scoped to its scheduling step.
: TASK-CHANGE-SOURCE DROP S" unreachable task source" SOURCE! 3 >IN ! ;
: TASK-SOURCE-FAIL TASK-CHANGE-SOURCE 97 THROW ;
: TASK-CHECK-SOURCE
  SOURCE 2>R >IN @ >R INPUT-PTR @ >R YIELD
  INPUT-PTR @ R> TASK-ASSERT= >IN @ R> TASK-ASSERT=
  SOURCE 2R> ROT TASK-ASSERT= TASK-ASSERT=
;
' TASK-CHANGE-SOURCE 0 TASK-NEW 1 TASK-ASSERT=
TASK-CHECK-SOURCE
1 TASK-FREE TASK-ASSERT
' TASK-SOURCE-FAIL 0 TASK-NEW 1 TASK-ASSERT=
TASK-CHECK-SOURCE
1 TASK-INFO 97 TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
TASK-INIT
\ A background evaluator cannot borrow a foreground compiler. Bracket
\ interpretation also owns the dictionary, even with a later complete entry.
: TASK-EVALUATOR
  DROP S" 777 TASK-A !" DROP EVALUATE0 THROW
  TASK-ID TASK-PAUSE DROP
;
: TASK-COMPILE-YIELD YIELD ; IMMEDIATE
0 TASK-A !
' TASK-EVALUATOR 0 TASK-NEW 1 TASK-ASSERT=
: TASK-FOREGROUND TASK-COMPILE-YIELD 123 ;
TASK-A @ 0 TASK-ASSERT=
TASK-FOREGROUND 123 TASK-ASSERT=
TASK-A @ 0 TASK-ASSERT=
YIELD TASK-A @ 777 TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 2 TASK-ASSERT=
0 TASK-A ! 1 TASK-RUN TASK-ASSERT
: TASK-BRACKET [ YIELD TASK-A @ 0 TASK-ASSERT= ] 456 ;
TASK-BRACKET 456 TASK-ASSERT=
TASK-A @ 0 TASK-ASSERT=
YIELD TASK-A @ 777 TASK-ASSERT=
0 TASK-A ! 1 TASK-RUN TASK-ASSERT
HERE LATEST @
: TASK-OUTER [ : TASK-INNER 789 ;
YIELD TASK-A @ 0 TASK-ASSERT=
\ Discard this deliberately unfinished outer definition, as shell recovery
\ does, and verify that callbacks resume after dictionary ownership ends.
LATEST ! DP ! 0 CP-DP ! CLEAR-FIND-CACHE
YIELD TASK-A @ 777 TASK-ASSERT=
TASK-INIT
\ Failed source may publish tasks before its unfinished dictionary entries
\ are rolled back. Clear both new code and new context references first.
VARIABLE TASK-ROLLBACK-HERE
VARIABLE TASK-ROLLBACK-ID
: TASK-ROLLBACK-SOURCE
  S" VARIABLE TASK-TEMP : TASK-TEMP-STEP DROP ; ' TASK-TEMP-STEP TASK-TEMP TASK-NEW TASK-ROLLBACK-ID ! : TASK-BROKEN [ 123 THROW"
  DROP EVALUATE0
;
: TASK-ROLLBACK-CONTEXT
  S" VARIABLE TASK-TEMP ' TASK-INC TASK-TEMP TASK-NEW TASK-ROLLBACK-ID ! : TASK-BROKEN"
  DROP EVALUATE0
;
' TASK-INC TASK-A TASK-NEW 1 TASK-ASSERT=
HERE TASK-ROLLBACK-HERE !
TASK-ROLLBACK-SOURCE 123 TASK-ASSERT=
HERE TASK-ROLLBACK-HERE @ TASK-ASSERT=
TASK-ROLLBACK-ID @ TASK-INFO
0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
TASK-ROLLBACK-CONTEXT 22 TASK-ASSERT=
HERE TASK-ROLLBACK-HERE @ TASK-ASSERT=
TASK-ROLLBACK-ID @ TASK-INFO
0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
0 TASK-A ! YIELD TASK-A @ 1 TASK-ASSERT=
1 TASK-INFO 0 TASK-ASSERT= 1 TASK-ASSERT= 1 TASK-ASSERT=
\ Shell recovery must call the same cleanup before reclaiming its line.
HERE SHELL-LINE-DP ! LATEST @ SHELL-LINE-LATEST !
VARIABLE TASK-TEMP
' TASK-INC TASK-TEMP TASK-NEW TASK-ROLLBACK-ID !
: TASK-BROKEN [ SHELL-ROLLBACK
HERE TASK-ROLLBACK-HERE @ TASK-ASSERT=
TASK-ROLLBACK-ID @ TASK-INFO
0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
YIELD TASK-A @ 2 TASK-ASSERT=
TASK-INIT
\ Opaque numeric contexts overlapping a reclaimed range are deliberately
\ treated as potential addresses. All occupied states must be cleared.
: TASK-RECLAIM-STATES
  6 1 DO
    ['] TASK-INC HERE TASK-NEW
    DUP I SWAP TASK-STATE! DROP
    HERE DUP 1+ TASK-RECLAIM
    TASK-INFO 0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
  LOOP
;
TASK-RECLAIM-STATES
' TASK-INC HERE 1+ TASK-NEW 1 TASK-ASSERT=
HERE DUP 1+ TASK-RECLAIM
1 TASK-INFO 0 TASK-ASSERT= 0 TASK-ASSERT= 1 TASK-ASSERT=
TASK-INIT
\ A callback using standard EVALUATE can fail or return normally with an
\ unfinished definition. Its compiler scope must not freeze other jobs.
: TASK-BAD-COMPILER DROP S" : TASK-ABANDONED NO-SUCH-WORD" EVALUATE ;
: TASK-OPEN-COMPILER DROP S" : TASK-ABANDONED" EVALUATE ;
: TASK-CHECK-COMPILER ( xt error -- )
  >R TASK-INIT 0 TASK-A !
  0 TASK-NEW 1 TASK-ASSERT=
  ['] TASK-INC TASK-A TASK-NEW 2 TASK-ASSERT=
  HERE TASK-ROLLBACK-HERE !
  YIELD HERE TASK-ROLLBACK-HERE @ TASK-ASSERT=
  1 TASK-INFO R> TASK-ASSERT= 1 TASK-ASSERT= 4 TASK-ASSERT=
  TASK-A @ 1 TASK-ASSERT=
  YIELD TASK-A @ 2 TASK-ASSERT=
  TASK-DICTIONARY (EVAL-PARTIAL?) 0 TASK-ASSERT=
;
' TASK-BAD-COMPILER 0 13 - TASK-CHECK-COMPILER
' TASK-OPEN-COMPILER 22 TASK-CHECK-COMPILER
TASK-INIT
\ Conservative cleanup can also clear the current job. Error recording must
\ not resurrect that slot with a zero callback xt.
' TASK-BAD-COMPILER HERE TASK-NEW 1 TASK-ASSERT=
YIELD 1 TASK-INFO 0 TASK-ASSERT= 0 TASK-ASSERT= 0 TASK-ASSERT=
1 TASK-RUN 0 TASK-ASSERT=
TASK-INIT
TASK-FAILURES @ . ." task failures / " TASK-TESTS @ . CR
