
: CO R> R> SWAP >R >R ;

: TOKYO
       ." HERE TOKYO OVER" CR CO
       ." WHAT GIVES? OVER" CR CO
       ." YES, MORE? OVER" CR CO
       ." OVER AND OUT" CR
 ;

: AMSTERDAM
   TOKYO
   ." HERE AMSTERDAM OVER" CR CO
   ." HAS IT ARRIVED OVER" CR CO
   ." NO. OVER AND OUT" CR

;

PAUSE PAGE
." EXPECT SENSIBLE CONVERSATION:" CR AMSTERDAM
