1 CONSTANT RIGHT
2 CONSTANT LEFT
3 CONSTANT UP
4 CONSTANT DOWN
VARIABLE CURX
VARIABLE CURY
VARIABLE CURR-CURSOR

: INC! 1 SWAP +! ;
: DEC! 1 SWAP -! ;

: INC-CURX CURX INC! ;
: INC-CURY CURY INC! ;

: DEC-CURX CURX @ IF CURX DEC! THEN ;
: DEC-CURY CURY @ IF CURY DEC! THEN ;

95 CONSTANT MAX-X
63 CONSTANT MAX-Y
: NORMALIZE-X CURX @ 0 MAX MAX-X MIN CURX ! ;
: NORMALIZE-Y CURY @ 0 MAX MAX-Y MIN CURY ! ;
: NORMALIZE-POS NORMALIZE-X NORMALIZE-Y ;
: KEY-TICK
  CASE
    RIGHT OF INC-CURX ENDOF
    LEFT  OF DEC-CURX ENDOF
    UP    OF INC-CURY ENDOF
    DOWN  OF DEC-CURY ENDOF
  ENDCASE
  NORMALIZE-POS
;

: DRAW-SQUARE ( X Y SIZE -- ) DUP RECT-XOR ;
: DRAW-CURSOR CURX @ CURY @ 10 DRAW-SQUARE ;

: DRAW-CURSOR-POS 0 0 AT-XY CURX ? CURY ? ;
: DRAW-TICK DRAW-CURSOR DRAW-CURSOR-POS ;
: ARROW-KEY? 1 4 WITHIN ;
: GET-ARROW-KEY BEGIN KEYC DUP ARROW-KEY? IF EXIT THEN DROP AGAIN ; 
: CURSOR-DEMO-TICK GET-ARROW-KEY PAGE KEY-TICK DRAW-TICK ;
: CURSOR-DEMO-INIT 0 CURX ! 0 CURY ! ;
: CURSOR-DEMO CURSOR-DEMO-INIT BEGIN CURSOR-DEMO-TICK AGAIN ;
