\ Interactive Forth shell loaded transiently from flash page 5.
\ Alphabetic input is the default; press 2ND before a digit or symbol.

\ Preserve the dictionary state so the shell can reclaim itself on exit.
CURRENT-INPUT-DEVICE @
CURRENT-ERROR-HANDLER @
CURRENT-EOF-HANDLER @
LATEST @
HERE
: SHELL-START ;
CONSTANT SHELL-BASE-DP
CONSTANT SHELL-BASE-LATEST
CONSTANT SHELL-BASE-EOF
CONSTANT SHELL-BASE-ERROR
CONSTANT SHELL-BASE-INPUT

1 VALUE SHELL-RUNNING

: BYE 0 TO SHELL-RUNNING ;

: HELP
  PAGE
  ." Forth shell" CR
  ." ENTER runs input." CR
  ." 2ND shifts one key." CR
  ." DEL backspaces." CR
  ." BYE opens the menu." CR
;

: SHELL-ERROR ( n -- )
  ." Error " . ." at " WORD-BUF PLOT-STRING CR
;

: SHELL-PROMPT ( -- flag )
  SHELL-RUNNING IF PROMPT ELSE 0 THEN
;

: SHELL-EOF
  SHELL-BASE-INPUT CURRENT-INPUT-DEVICE !
  SHELL-BASE-ERROR CURRENT-ERROR-HANDLER !
  SHELL-BASE-EOF CURRENT-EOF-HANDLER !
  SHELL-BASE-LATEST LATEST !
  SHELL-BASE-DP DP !
  MENU-DEMO
;

PAGE
." zkeme80 Forth" CR
." Type HELP for help." CR CR

' SHELL-PROMPT CURRENT-INPUT-DEVICE !
' SHELL-ERROR CURRENT-ERROR-HANDLER !
' SHELL-EOF CURRENT-EOF-HANDLER !
