\ Interactive Forth shell loaded transiently from flash page 5.
\ Alphabetic input is the default; press 2ND before a digit or symbol.

\ Preserve the dictionary state so the shell can reclaim itself on exit.
EDIT-HISTORY @
CURRENT-INPUT-DEVICE @
CURRENT-ERROR-HANDLER @
CURRENT-EOF-HANDLER @
LATEST @
HERE
: SHELL-START ;
CONSTANT SHELL-BASE-DP
CONSTANT SHELL-BASE-LATEST
CONSTANT SHELL-BASE-EOF
CONSTANT SHELL-BASE-ERROR
CONSTANT SHELL-BASE-INPUT
CONSTANT SHELL-BASE-EDIT-HISTORY

\ History is a 512-entry metadata ring over a 4096-byte text ring.  A line
\ may use the editor's full 128-byte capacity; oldest entries are evicted
\ when their combined text no longer fits, while short commands can retain
\ the requested 512 entries.
CREATE SHELL-HISTORY-OFFSETS 1024 ALLOT
CREATE SHELL-HISTORY-LENGTHS 512 ALLOT
CREATE SHELL-HISTORY-DATA 4096 ALLOT
CREATE SHELL-HISTORY-DRAFT 129 ALLOT

VARIABLE SHELL-HISTORY-HEAD
VARIABLE SHELL-HISTORY-COUNT
VARIABLE SHELL-HISTORY-DATA-HEAD
VARIABLE SHELL-HISTORY-DATA-USED
VARIABLE SHELL-HISTORY-NAV
VARIABLE SHELL-HISTORY-DEST
VARIABLE SHELL-HISTORY-CAPACITY
VARIABLE SHELL-HISTORY-WRITE-SLOT

: SHELL-HISTORY-SLOT ( age -- slot )
  SHELL-HISTORY-HEAD @ SWAP - 1- 511 AND
;

: SHELL-HISTORY-OLDEST ( -- slot )
  SHELL-HISTORY-HEAD @ SHELL-HISTORY-COUNT @ - 511 AND
;

: SHELL-HISTORY-DROP-OLDEST ( -- )
  SHELL-HISTORY-OLDEST SHELL-HISTORY-LENGTHS + C@
  NEGATE SHELL-HISTORY-DATA-USED +!
  -1 SHELL-HISTORY-COUNT +!
;

: SHELL-HISTORY-MAKE-ROOM ( u -- u )
  BEGIN
    DUP SHELL-HISTORY-DATA-USED @ + 4096 >
    SHELL-HISTORY-COUNT @ 512 = OR
  WHILE
    SHELL-HISTORY-DROP-OLDEST
  REPEAT
;

: LINE>HISTORY ( c-addr offset u -- )
  0 DO
    OVER I + C@
    OVER I + 4095 AND SHELL-HISTORY-DATA + C!
  LOOP
  2DROP
;

: HISTORY>LINE ( offset c-addr u -- )
  0 DO
    OVER I + 4095 AND SHELL-HISTORY-DATA + C@
    OVER I + C!
  LOOP
  2DROP
;

: SHELL-HISTORY-ADD ( c-addr u -- )
  128 MIN
  DUP 0= IF 2DROP 0 SHELL-HISTORY-NAV ! EXIT THEN
  DUP SHELL-HISTORY-MAKE-ROOM DROP
  SHELL-HISTORY-HEAD @ DUP SHELL-HISTORY-WRITE-SLOT !
  CELLS SHELL-HISTORY-OFFSETS +
  SHELL-HISTORY-DATA-HEAD @ SWAP !
  DUP SHELL-HISTORY-WRITE-SLOT @ SHELL-HISTORY-LENGTHS + C!
  DUP >R SHELL-HISTORY-DATA-HEAD @ SWAP LINE>HISTORY
  SHELL-HISTORY-DATA-HEAD @ R@ + 4095 AND SHELL-HISTORY-DATA-HEAD !
  R@ SHELL-HISTORY-DATA-USED +! RDROP
  SHELL-HISTORY-HEAD @ 1+ 511 AND SHELL-HISTORY-HEAD !
  1 SHELL-HISTORY-COUNT +!
  0 SHELL-HISTORY-NAV !
;

: SHELL-HISTORY-SAVE-DRAFT ( u -- )
  DUP SHELL-HISTORY-DRAFT C!
  SHELL-HISTORY-DEST @ SHELL-HISTORY-DRAFT 1+ ROT CMOVE
;

: SHELL-HISTORY-LOAD-DRAFT ( -- u )
  SHELL-HISTORY-DRAFT COUNT
  SHELL-HISTORY-CAPACITY @ MIN DUP >R
  SHELL-HISTORY-DEST @ SWAP CMOVE R>
;

: SHELL-HISTORY-LOAD-SLOT ( slot -- u )
  DUP CELLS SHELL-HISTORY-OFFSETS + @
  SWAP SHELL-HISTORY-LENGTHS + C@
  SHELL-HISTORY-CAPACITY @ MIN DUP >R
  SHELL-HISTORY-DEST @ SWAP HISTORY>LINE R>
;

: SHELL-HISTORY-UP ( used -- used' )
  SHELL-HISTORY-COUNT @ 0= IF EXIT THEN
  SHELL-HISTORY-NAV @ 0= IF DUP SHELL-HISTORY-SAVE-DRAFT THEN
  SHELL-HISTORY-NAV @ SHELL-HISTORY-COUNT @ < IF
    DROP 1 SHELL-HISTORY-NAV +!
    SHELL-HISTORY-NAV @ 1- SHELL-HISTORY-SLOT SHELL-HISTORY-LOAD-SLOT
  THEN
;

: SHELL-HISTORY-DOWN ( used -- used' )
  SHELL-HISTORY-NAV @ 0= IF EXIT THEN
  DROP -1 SHELL-HISTORY-NAV +!
  SHELL-HISTORY-NAV @ 0= IF
    SHELL-HISTORY-LOAD-DRAFT
  ELSE
    SHELL-HISTORY-NAV @ 1- SHELL-HISTORY-SLOT SHELL-HISTORY-LOAD-SLOT
  THEN
;

: SHELL-HISTORY-EDIT ( c-addr capacity used direction -- used' )
  >R ROT SHELL-HISTORY-DEST ! SWAP SHELL-HISTORY-CAPACITY ! R>
  0< IF SHELL-HISTORY-UP ELSE SHELL-HISTORY-DOWN THEN
;

1 VALUE SHELL-RUNNING

: BYE 0 TO SHELL-RUNNING ;

: HELP
  PAGE
  ." Forth shell" CR
  ." ENTER runs input." CR
  ." LEFT/RIGHT move." CR
  ." UP/DOWN show history." CR
  ." DEL backspaces." CR
  ." 2ND shifts; BYE exits." CR
;

: SHELL-ERROR ( n -- )
  ." Error " . ." at " TOKEN-BUF PLOT-STRING CR
;

: SHELL-PROMPT ( -- flag )
  SHELL-RUNNING IF
    BEGIN CUR-ROW @ 48 > WHILE SCROLL REPEAT
    ." > " PBUF 128 EDIT-LINE
    PBUF SPAN @ 2DUP SHELL-HISTORY-ADD SOURCE! 1
  ELSE
    0
  THEN
;

: SHELL-EOF
  SHELL-BASE-INPUT CURRENT-INPUT-DEVICE !
  SHELL-BASE-ERROR CURRENT-ERROR-HANDLER !
  SHELL-BASE-EOF CURRENT-EOF-HANDLER !
  SHELL-BASE-EDIT-HISTORY EDIT-HISTORY !
  SHELL-BASE-LATEST LATEST !
  SHELL-BASE-DP DP !
  MENU-DEMO
;

PAGE
." zkeme80 Forth" CR
." Type HELP for help." CR CR

' SHELL-PROMPT CURRENT-INPUT-DEVICE !
' SHELL-ERROR CURRENT-ERROR-HANDLER !
' SHELL-EOF CURRENT-EOF-HANDLER !
' SHELL-HISTORY-EDIT EDIT-HISTORY !
