\ Resident Forth workspace; definitions and history survive desktop visits.
\ Alphabetic input is the default; press 2ND before a digit or symbol.

\ History is a 512-entry metadata ring over a 4096-byte text ring.  A line
\ may use the editor's full 128-byte capacity; oldest entries are evicted
\ when their combined text no longer fits, while short commands can retain
\ the requested 512 entries.
16384 CONSTANT SHELL-HISTORY-OFFSETS
17408 CONSTANT SHELL-HISTORY-LENGTHS
17920 CONSTANT SHELL-HISTORY-DATA
22016 CONSTANT SHELL-HISTORY-DRAFT

VARIABLE SHELL-HISTORY-HEAD
VARIABLE SHELL-HISTORY-COUNT
VARIABLE SHELL-HISTORY-DATA-HEAD
VARIABLE SHELL-HISTORY-DATA-USED
VARIABLE SHELL-HISTORY-NAV
VARIABLE SHELL-HISTORY-DEST
VARIABLE SHELL-HISTORY-CAPACITY
VARIABLE SHELL-HISTORY-WRITE-SLOT

: SHELL-HISTORY-SLOT ( age -- slot )
  SHELL-HISTORY-HEAD @ SWAP - 1- 511 AND
;

: SHELL-HISTORY-OLDEST ( -- slot )
  SHELL-HISTORY-HEAD @ SHELL-HISTORY-COUNT @ - 511 AND
;

: SHELL-HISTORY-DROP-OLDEST ( -- )
  SHELL-HISTORY-OLDEST SHELL-HISTORY-LENGTHS + C@
  NEGATE SHELL-HISTORY-DATA-USED +!
  -1 SHELL-HISTORY-COUNT +!
;

: SHELL-HISTORY-MAKE-ROOM ( u -- u )
  BEGIN
    DUP SHELL-HISTORY-DATA-USED @ + 4096 >
    SHELL-HISTORY-COUNT @ 512 = OR
  WHILE
    SHELL-HISTORY-DROP-OLDEST
  REPEAT
;

: LINE>HISTORY ( c-addr offset u -- )
  0 DO
    OVER I + C@
    OVER I + 4095 AND SHELL-HISTORY-DATA + C!
  LOOP
  2DROP
;

: HISTORY>LINE ( offset c-addr u -- )
  0 DO
    OVER I + 4095 AND SHELL-HISTORY-DATA + C@
    OVER I + C!
  LOOP
  2DROP
;

: (HISTORY-ADD) ( c-addr u -- )
  128 MIN
  DUP 0= IF 2DROP 0 SHELL-HISTORY-NAV ! EXIT THEN
  DUP SHELL-HISTORY-MAKE-ROOM DROP
  SHELL-HISTORY-HEAD @ DUP SHELL-HISTORY-WRITE-SLOT !
  CELLS SHELL-HISTORY-OFFSETS +
  SHELL-HISTORY-DATA-HEAD @ SWAP !
  DUP SHELL-HISTORY-WRITE-SLOT @ SHELL-HISTORY-LENGTHS + C!
  DUP >R SHELL-HISTORY-DATA-HEAD @ SWAP LINE>HISTORY
  SHELL-HISTORY-DATA-HEAD @ R@ + 4095 AND SHELL-HISTORY-DATA-HEAD !
  R@ SHELL-HISTORY-DATA-USED +! RDROP
  SHELL-HISTORY-HEAD @ 1+ 511 AND SHELL-HISTORY-HEAD !
  1 SHELL-HISTORY-COUNT +!
  0 SHELL-HISTORY-NAV !
;

: SHELL-HISTORY-SAVE-DRAFT ( u -- )
  DUP SHELL-HISTORY-DRAFT C!
  SHELL-HISTORY-DEST @ SHELL-HISTORY-DRAFT 1+ ROT CMOVE
;

: SHELL-HISTORY-LOAD-DRAFT ( -- u )
  SHELL-HISTORY-DRAFT COUNT
  SHELL-HISTORY-CAPACITY @ MIN DUP >R
  SHELL-HISTORY-DEST @ SWAP CMOVE R>
;

: SHELL-HISTORY-LOAD-SLOT ( slot -- u )
  DUP CELLS SHELL-HISTORY-OFFSETS + @
  SWAP SHELL-HISTORY-LENGTHS + C@
  SHELL-HISTORY-CAPACITY @ MIN DUP >R
  SHELL-HISTORY-DEST @ SWAP HISTORY>LINE R>
;

: SHELL-HISTORY-UP ( used -- used' )
  SHELL-HISTORY-COUNT @ 0= IF EXIT THEN
  SHELL-HISTORY-NAV @ 0= IF DUP SHELL-HISTORY-SAVE-DRAFT THEN
  SHELL-HISTORY-NAV @ SHELL-HISTORY-COUNT @ < IF
    DROP 1 SHELL-HISTORY-NAV +!
    SHELL-HISTORY-NAV @ 1- SHELL-HISTORY-SLOT SHELL-HISTORY-LOAD-SLOT
  THEN
;

: SHELL-HISTORY-DOWN ( used -- used' )
  SHELL-HISTORY-NAV @ 0= IF EXIT THEN
  DROP -1 SHELL-HISTORY-NAV +!
  SHELL-HISTORY-NAV @ 0= IF
    SHELL-HISTORY-LOAD-DRAFT
  ELSE
    SHELL-HISTORY-NAV @ 1- SHELL-HISTORY-SLOT SHELL-HISTORY-LOAD-SLOT
  THEN
;

: (HISTORY-EDIT) ( c-addr capacity used direction -- used' )
  >R ROT SHELL-HISTORY-DEST ! SWAP SHELL-HISTORY-CAPACITY ! R>
  0< IF SHELL-HISTORY-UP ELSE SHELL-HISTORY-DOWN THEN
;

\ RAM page 2 belongs to history. Callers and line buffers live in fixed RAM;
\ restore the foreground mapping even when an editor operation throws.
: SHELL-HISTORY-ADD ( c-addr u -- )
  BANK@ >R 130 (BANK!) ['] (HISTORY-ADD) CATCH R> (BANK!) THROW ;
: SHELL-HISTORY-EDIT ( c-addr capacity used direction -- used' )
  BANK@ >R 130 (BANK!) ['] (HISTORY-EDIT) CATCH R> (BANK!) THROW ;

VARIABLE SHELL-RUNNING
VARIABLE SHELL-LINE-DP
VARIABLE SHELL-LINE-LATEST
1 SHELL-RUNNING !

: BYE 0 SHELL-RUNNING ! ;

: FILES FS-LIST ;
: SERVICES OS-SERVICES ;
: HELP
  PAGE
  ." Forth shell" CR
  ." ENTER runs input." CR
  ." LEFT/RIGHT move." CR
  ." UP/DOWN show history." CR
  ." DEL backspaces." CR
  ." 2ND shifts; BYE exits." CR
;

\ Bracket interpretation and nested definitions remain inside the original
\ prompt transaction until every newly created definition is complete.
: SHELL-COMPILING? ( -- flag )
  STATE @ SHELL-LINE-LATEST @ (EVAL-PARTIAL?) OR ;
: SHELL-ROLLBACK ( -- )
  SHELL-COMPILING? IF
    SHELL-LINE-DP @ DP ! SHELL-LINE-LATEST @ LATEST !
    0 CP-DP ! 0 CP-LOOPS ! CLEAR-FIND-CACHE
  THEN 0 STATE ! ;
: SHELL-ERROR ( n -- )
  ." Error " . ." at " TOKEN-BUF PLOT-STRING CR SHELL-ROLLBACK
;

: SHELL-PROMPT ( -- flag )
  YIELD SHELL-RUNNING @ IF
    SHELL-COMPILING? 0= IF
      HERE SHELL-LINE-DP ! LATEST @ SHELL-LINE-LATEST !
    THEN
    BEGIN CUR-ROW @ 48 > WHILE SCROLL REPEAT
    ." > " PBUF 128 EDIT-LINE
    PBUF SPAN @ 2DUP SHELL-HISTORY-ADD SOURCE! 1
  ELSE
    0
  THEN
;

: SHELL-EOF SHELL-ROLLBACK MENU-DEMO ;
: SHELL-OPEN
  HERE SHELL-LINE-DP ! LATEST @ SHELL-LINE-LATEST !
  1 SHELL-RUNNING !
  ['] SHELL-PROMPT CURRENT-INPUT-DEVICE !
  ['] SHELL-ERROR CURRENT-ERROR-HANDLER !
  ['] SHELL-EOF CURRENT-EOF-HANDLER !
  ['] SHELL-HISTORY-EDIT EDIT-HISTORY !
  0 0 SOURCE!
  PAGE ." zkeme80 Forth" CR ." Type HELP for help." CR CR
;
' SHELL-OPEN WORKBENCH-XT !
