(define flash-asm
  `((label write-flash-byte)
    (push bc)
    (ld b a)
    (push af)
    (ld a i)
    (push af)
    (di)
    (ld a b)
    ,@(push* '(hl de bc hl de bc))

    (ld hl write-flash-byte-ram)
    (ld de flash-executable-ram)
    (ld bc #x1f)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    ,@(pop* '(bc de hl af))
    (jp po local-label1)
    (ei)
    (label local-label1)
    ,@(pop* '(af bc))
    (ret)
    (label write-flash-byte-ram)
    (and (hl))
    (ld b a)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld (hl) b)
    (label local-label2)
    (ld a b)
    (xor (hl))
    (bit 7 a)
    (jr z write-flash-byte-done)
    (bit 5 (hl))
    (jr z local-label2)
    (label write-flash-byte-done)
    (ld (hl) #xf0)
    (ret)

    (label write-flash-byte-ram-end)

    (label write-flash-buffer)
    (push af)
    (ld a i)
    (push af)
    (di)
    ,@(push* '(hl de bc hl de bc))
    (ld hl write-flash-buffer-ram)
    (ld de flash-executable-ram)
    ;; Keep this in sync with write-flash-buffer-ram through its end label.
    (ld bc #x3c)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    (ld (flash-operation-status) a)
    ,@(pop* '(bc de hl af))
    (jp po local-label3)
    (ei)
    (label local-label3)
    (pop af)
    (ld a (flash-operation-status))
    (or a)
    (ret)

    (label write-flash-buffer-ram)
    (ld a b)
    (or c)
    (jr z write-flash-buffer-success)
    (label write-flash-buffer-loop)
    (ld a #xaa)
    (ld (#xaaa) a)
    (ld a #x55)
    (ld (#x555) a)
    (ld a #xa0)
    (ld (#xaaa) a)
    (ld a (hl))
    (ld (de) a)

    (label local-label4)
    (ld a (de))
    (xor (hl))
    (bit 7 a)
    (jr z local-label5)
    (ld a (de))
    (bit 5 a)
    (jr z local-label4)
    ;; DQ5 set: DQ7 gets one final check before timeout.
    (ld a (de))
    (xor (hl))
    (bit 7 a)
    (jr z local-label5)
    (ld a #xf0)
    (ld (0) a)
    (xor a)
    (ret)
    (label local-label5)
    (inc hl)
    (inc de)
    (dec bc)
    (ld a b)
    (or a)
    (jr nz write-flash-buffer-loop)
    (ld a c)
    (or a)
    (jr nz write-flash-buffer-loop)
    (label write-flash-buffer-success)
    (ld a 1)
    (or a)
    (ret)

    (label write-flash-buffer-ram-end)

    (label erase-flash-sector)
    (push bc)
    (ld b a)
    (push af)
    (ld a i)
    (ld a i)
    (push af)
    (di)
    (ld a b)
    ,@(push* '(hl de bc hl de bc))
    (ld hl erase-flash-sector-ram)
    (ld de flash-executable-ram)
    ;; Keep this in sync with erase-flash-sector-ram through its end label.
    (ld bc #x3d)
    (ldir)
    ,@(pop* '(bc de hl))
    (call flash-executable-ram)
    (ld (flash-operation-status) a)
    ,@(pop* '(bc de hl af))
    (jp po local-label6)
    (ei)
    (label local-label6)
    (pop af)
    (pop bc)
    (ld a (flash-operation-status))
    (or a)
    (ret)

    (label erase-flash-sector-ram)
    (out (6) a)
    (ld a #xaa)
    (ld (#x0aaa) a)
    (ld a #x55)
    (ld (#x0555) a)
    (ld a #x80)
    (ld (#x0aaa) a)
    (ld a #xaa)
    (ld (#x0aaa) a)
    (ld a #x55)
    (ld (#x0555) a)
    (ld a #x30)
    (ld (#x4000) a)
    (label local-label7)
    (ld a (#x4000))
    (bit 7 a)
    (jr nz erase-flash-sector-success)
    (bit 5 a)
    (jr z local-label7)
    ;; DQ5 set: DQ7 gets one final check before timeout.
    (ld a (#x4000))
    (bit 7 a)
    (jr nz erase-flash-sector-success)
    (ld a #xf0)
    (ld (#x4000) a)
    (xor a)
    (ret)
    (label erase-flash-sector-success)
    (ld a 1)
    (or a)
    (ret)
    (label erase-flash-sector-ram-end)

    ))
