(define interrupt-asm
  `((label sys-interrupt)
    (di)
    ,@(push* '(af bc de hl ix iy))
    (exx)
    ((ex af afs))
    ,@(push* '(af bc de hl))
    (jp usb-interrupt)
    (label interrupt-resume)
    (in a (4))
    (bit 0 a)
    (jr nz int-handle-on)
    (bit 1 a)
    (jr nz int-handle-timer1)
    (bit 2 a)
    (jr nz int-handle-timer2)
    (bit 4 a)
    (jr nz int-handle-link)
    (jr sys-interrupt-done)

    (label int-handle-on)
    (in a (3))
    (res 0 a)
    (out (3) a)
    (set 0 a)
    (out (3) a)
    (jr sys-interrupt-done)

    (label int-handle-timer1)
    (in a (3))
    (res 1 a)
    (out (3) a)
    (set 1 a)
    (out (3) a)
    (jr sys-interrupt-done)

    (label int-handle-timer2)
    (in a (3))
    (res 2 a)
    (out (3) a)
    (set 2 a)
    (out (3) a)
    (jr sys-interrupt-done)

    (label int-handle-link)
    (in a (3))
    (res 4 a)
    (out (3) a)
    (set 4 a)
    (out (3) a)

    (label sys-interrupt-done)

    ,@(pop* '(hl de bc af))
    (exx)
    ((ex af afs))
    ,@(pop* '(iy ix hl de bc af))
    (ei)
    (ret)
    (label usb-interrupt)
    (in a (#x55))
    (bit 0 a)
    (jr z usb-unknown-event)
    (bit 2 a)
    (jr z usb-line-event)
    (bit 4 a)
    (jr z usb-protocol-event)
    (jp interrupt-resume)
    (label usb-unknown-event)
    (jp interrupt-resume)
    (label usb-line-event)

    (in a (#x56))
    (xor #xff)
    (out (#x57) a)
    (jp interrupt-resume)

    (label usb-protocol-event)
    ,@(map (lambda (x) `(in a (,x)))
           '(#x82 #x83 #x84 #x85 #x86))

    (jp interrupt-resume)
    ))
