\ Resident navigator: views use the same yielding key loop as the workspace.
VARIABLE OS-CHOICE
VARIABLE OS-PAGE-NO
VARIABLE OS-PAGE-MODE
VARIABLE OS-TASK-ID
VARIABLE OS-SERVICE-FIRST
VARIABLE OS-FILE-NO
VARIABLE OS-FILE-OFFSET
VARIABLE OS-NOTICE
0 OS-CHOICE ! 0 OS-PAGE-NO ! 0 OS-PAGE-MODE !
1 OS-TASK-ID ! 0 OS-SERVICE-FIRST !
0 OS-FILE-NO ! 0 OS-FILE-OFFSET ! 0 OS-NOTICE !
: OS-KEY ( -- key ) KEY-EVENT ;
: OS-BACK? ( key -- flag ) DUP 15 = SWAP 50 = OR ;

: OS-FILE-TEXT ( -- )
  OS-FILE-NO @ FS-NTH IF
    2DROP FS-GET IF DROP 2DROP 2 12 AT-XY ." Read error" ELSE
      DROP DUP IF DUP 1- 96 / 96 * ELSE 0 THEN
      OS-FILE-OFFSET @ MIN DUP OS-FILE-OFFSET !
      ROT OVER + -ROT - 96 MIN
      ?DUP IF 0 DO
        2 I 16 MOD 5 * + I 16 / 7 * 12 + AT-XY
        DUP I + C@ OS-PRINTABLE EMIT
      LOOP ELSE 2 12 AT-XY ." Empty object" THEN DROP
    THEN
  ELSE 2DROP 2DROP THEN ;
: OS-FILE-LOAD ( -- )
  OS-FILE-NO @ FS-NTH IF
    2 = IF DROP FS-LOAD IF 4 ELSE 3 THEN OS-NOTICE !
    ELSE DROP 2DROP THEN
  ELSE 2DROP 2DROP THEN ;
: OS-FILE-VIEW ( -- )
  0 OS-FILE-OFFSET ! 0 OS-NOTICE !
  BEGIN
    OS-FILE-NO @ FS-NTH IF 2DROP OS-TITLE
    ELSE 2DROP 2DROP S" OBJECT" OS-TITLE THEN OS-FILE-TEXT
    OS-FOOT OS-NOTICE @ CASE
      3 OF ." Loaded / CLR back" ENDOF
      4 OF ." Load error / CLR back" ENDOF
      0 OF OS-FILE-NO @ FS-NTH IF
        2 = >R DROP 2DROP R> IF ." <> page ENT load CLR"
        ELSE ." <> page CLR back" THEN
        ELSE 2DROP 2DROP THEN ENDOF
    ENDCASE
    OS-KEY DUP OS-BACK? IF DROP EXIT THEN
    CASE
      LEFT OF OS-FILE-OFFSET @ 96 >= IF 96 OS-FILE-OFFSET -! THEN ENDOF
      RIGHT OF 96 OS-FILE-OFFSET +! ENDOF
      9 OF OS-FILE-LOAD ENDOF
    ENDCASE
  AGAIN ;
: OS-FILE-KIND ( type -- )
  CASE 1 OF 84 ENDOF 2 OF 70 ENDOF 3 OF 66 ENDOF
    63 SWAP ENDCASE EMIT ;
: OS-FILE-DRAW ( -- )
  FS-COUNT DUP IF 1- OS-FILE-NO @ MIN THEN OS-FILE-NO !
  S" FILES" OS-TITLE
  2 11 AT-XY FS-COUNT OS-NUM ." objects " FS-FREE OS-NUM ." free"
  FS-COUNT IF
    4 0 DO
      OS-FILE-NO @ 4 / 4 * I + DUP FS-COUNT < IF
        DUP FS-NTH IF
          4 I 8 * 20 + AT-XY OS-FILE-KIND DROP
          14 I 8 * 20 + AT-XY OS-LABEL
        ELSE 2DROP 2DROP THEN
        OS-FILE-NO @ = IF I 8 * 20 + OS-SELECT THEN
      ELSE DROP THEN
    LOOP
    2 50 AT-XY OS-FILE-NO @ 1+ OS-NUM ." / " FS-COUNT OS-NUM
  ELSE 8 27 AT-XY ." No saved objects"
    8 38 AT-XY ." Save with FS-PUT"
  THEN
  OS-FOOT ." ^v ENT view CLR back" ;
: OS-FILES ( -- )
  BEGIN
    OS-FILE-DRAW OS-KEY DUP OS-BACK? IF DROP EXIT THEN
    CASE
      UP OF OS-FILE-NO @ IF 1 OS-FILE-NO -! THEN ENDOF
      DOWN OF OS-FILE-NO @ 1+ FS-COUNT < IF 1 OS-FILE-NO +! THEN ENDOF
      9 OF OS-FILE-NO @ FS-COUNT < IF OS-FILE-VIEW THEN ENDOF
    ENDCASE
  AGAIN ;

: OS-TASK-STATE ( state -- )
  CASE
    0 OF ." free" ENDOF 1 OF ." ready" ENDOF
    2 OF ." paused" ENDOF 3 OF ." stopped" ENDOF
    4 OF ." failed" ENDOF 5 OF ." waiting" ENDOF
  ENDCASE ;
: OS-TASK-DRAW ( -- )
  S" TASKS / STEPS" OS-TITLE
  TASK-LIMIT 0 DO
    4 I 8 * 13 + AT-XY I 1+ OS-NUM
    I 1+ TASK-INFO DROP SWAP
    15 I 8 * 13 + AT-XY OS-TASK-STATE
    68 I 8 * 13 + AT-XY OS-NUM
    I 1+ OS-TASK-ID @ = IF I 8 * 13 + OS-SELECT THEN
  LOOP
  2 47 AT-XY OS-NOTICE @ 1 = IF ." Task table full" ELSE
    OS-TASK-ID @ TASK-INFO ." Error " OS-NUM 2DROP
    ." >new <stop"
  THEN
  OS-FOOT ." ^v ENT run/pause CLR" ;
: OS-TASKS ( -- )
  0 OS-NOTICE !
  BEGIN
    OS-TASK-DRAW OS-KEY DUP OS-BACK? IF DROP EXIT THEN
    CASE
      UP OF OS-TASK-ID @ 1 > IF 1 OS-TASK-ID -! THEN ENDOF
      DOWN OF OS-TASK-ID @ TASK-LIMIT < IF 1 OS-TASK-ID +! THEN ENDOF
      RIGHT OF TASK-DEMO ?DUP IF OS-TASK-ID ! 0 ELSE 1 THEN OS-NOTICE ! ENDOF
      LEFT OF OS-TASK-ID @ TASK-STOP DROP ENDOF
      56 OF OS-TASK-ID @ TASK-FREE DROP 0 OS-NOTICE ! ENDOF
      9 OF OS-TASK-ID @ TASK-INFO 2DROP 1 = IF
        OS-TASK-ID @ TASK-PAUSE ELSE OS-TASK-ID @ TASK-RUN
        THEN DROP ENDOF
    ENDCASE
  AGAIN ;

: OS-PAGE-USED? ( page -- flag )
  DUP 0= OVER 2 = OR OVER STORAGE-PAGE = OR
  OVER 6 = OR OVER 56 >= OR SWAP
  DUP MODULE-CORE = OVER MODULE-STORAGE = OR
  OVER MODULE-DESKTOP = OR OVER MODULE-WORKBENCH = OR
  SWAP MODULE-TESTS = OR OR ;
: OS-PAGE-NAME ( -- )
  OS-PAGE-NO @ CASE
    0 OF ." kernel" ENDOF 2 OF ." RAM init" ENDOF
    6 OF ." image" ENDOF
    MODULE-CORE OF ." core" ENDOF
    MODULE-STORAGE OF ." storage" ENDOF
    MODULE-DESKTOP OF ." desktop" ENDOF
    MODULE-WORKBENCH OF ." forth" ENDOF
    MODULE-TESTS OF ." tests" ENDOF
    STORAGE-PAGE OF ." objects" ENDOF
    DUP 56 >= IF ." system" ELSE ." unused" THEN
  ENDCASE ;
: OS-PAGE-MAP ( -- )
  64 0 DO
    3 I 8 MOD 6 * + 12 I 8 / 5 * +
    I OS-PAGE-USED? IF 4 3 RECT-OR ELSE 1 1 RECT-OR THEN
    I OS-PAGE-NO @ = IF
      2 I 8 MOD 6 * + 11 I 8 / 5 * + 6 5 RECT-XOR
    THEN
  LOOP
  54 12 AT-XY ." Page " OS-PAGE-NO @ OS-NUM
  54 22 AT-XY OS-PAGE-NAME
  54 34 AT-XY ." Free RAM"
  54 43 AT-XY UNUSED OS-NUM
  54 50 38 1 RECT-OR ;
: OS-PAGE-TEXT ( -- )
  6 0 DO
    3 I 7 * 12 + AT-XY I 4 * OS-BYTE ." : "
    4 0 DO MEMA J 4 * + I + C@ OS-BYTE SPACE LOOP
  LOOP ;
: OS-PAGE-DRAW ( -- )
  S" MEMORY" OS-TITLE
  OS-PAGE-MODE @ IF
    ['] OS-PAGE-TEXT OS-PAGE-NO @ WITH-PAGE DROP
  ELSE OS-PAGE-MAP THEN
  OS-FOOT ." <> page ENT map/hex" ;
: OS-PAGES ( -- )
  BEGIN
    OS-PAGE-DRAW OS-KEY DUP OS-BACK? IF DROP EXIT THEN
    CASE
      LEFT OF OS-PAGE-NO @ IF 1 OS-PAGE-NO -! THEN ENDOF
      RIGHT OF OS-PAGE-NO @ 63 < IF 1 OS-PAGE-NO +! THEN ENDOF
      UP OF OS-PAGE-NO @ 8 >= IF 8 OS-PAGE-NO -! ELSE 0 OS-PAGE-NO ! THEN ENDOF
      DOWN OF OS-PAGE-NO @ 8 + 63 MIN OS-PAGE-NO ! ENDOF
      9 OF OS-PAGE-MODE @ 0= OS-PAGE-MODE ! ENDOF
    ENDCASE
  AGAIN ;
: OS-SERVICE-DRAW ( -- )
  S" SYSTEM CALLS / V1" OS-TITLE
  6 0 DO
    OS-SERVICE-FIRST @ I + DUP SERVICE-COUNT < IF
      3 I 7 * 12 + AT-XY DUP OS-NUM
      16 I 7 * 12 + AT-XY SERVICE@ ?DUP IF CFA> ID. THEN
    ELSE DROP THEN
  LOOP
  OS-FOOT ." <> browse CLR back" ;
: OS-SERVICES ( -- )
  BEGIN
    OS-SERVICE-DRAW OS-KEY DUP OS-BACK? IF DROP EXIT THEN
    CASE
      LEFT OF OS-SERVICE-FIRST @ 6 >= IF 6 OS-SERVICE-FIRST -! THEN ENDOF
      RIGHT OF OS-SERVICE-FIRST @ 6 + SERVICE-COUNT < IF
        6 OS-SERVICE-FIRST +! THEN ENDOF
    ENDCASE
  AGAIN ;
: OS-ITEM ( index -- )
  CASE
    0 OF ." Workspace" ENDOF
    1 OF ." Files" ENDOF
    2 OF ." Tasks" ENDOF
    3 OF ." Memory" ENDOF
    4 OF ." Services" ENDOF
    5 OF ." Tests" ENDOF
    6 OF ." Power off" ENDOF
  ENDCASE ;
: OS-FIRST ( -- index ) OS-CHOICE @ 4 > IF OS-CHOICE @ 4 - ELSE 0 THEN ;
: OS-DRAW ( -- )
  PAGE
  10 TO ZKEME80-LOGO-STARTX 28 TO ZKEME80-LOGO-STARTY ZKEME80-LOGO
  3 47 AT-XY UNUSED 1024 / OS-NUM ." K free"
  35 0 1 54 RECT-OR
  40 2 AT-XY ." APPS"
  78 2 AT-XY OS-CHOICE @ 49 + EMIT ." /7"
  37 0 59 9 RECT-XOR
  5 0 DO
    OS-FIRST I +
    40 I 8 * 13 + AT-XY DUP OS-ITEM
    OS-CHOICE @ = IF 38 I 8 * 12 + 51 7 RECT-XOR THEN
  LOOP
  93 12 1 39 RECT-OR
  92 OS-FIRST 6 * 12 + 3 27 RECT-OR
  OS-FOOT ." ^v select ENT open" ;
: MENU-DEMO ( -- )
  BEGIN
    OS-DRAW OS-KEY
    CASE
      UP OF OS-CHOICE @ IF 1 OS-CHOICE -! THEN ENDOF
      DOWN OF OS-CHOICE @ 6 < IF 1 OS-CHOICE +! THEN ENDOF
      9 OF OS-CHOICE @ CASE
        0 OF LOAD-SHELL EXIT ENDOF
        1 OF OS-FILES ENDOF
        2 OF OS-TASKS ENDOF
        3 OF OS-PAGES ENDOF
        4 OF OS-SERVICES ENDOF
        5 OF LOAD-TEST-SUITE EXIT ENDOF
        6 OF POWEROFF ENDOF
      ENDCASE ENDOF
    ENDCASE
  AGAIN ;
